window.CONTENT_DATA = {
  themes: [
    {
      id: "chilan-river",
      title: "赤蘭溪流域文化",
      description: "請在這裡補上主題簡介。",
      coverImage: "public/images/themes/chilan-river/cover.jpg",
      gallery: [
        "public/images/themes/chilan-river/01.jpg",
        "public/images/themes/chilan-river/02.jpg",
      ],
      documents: [],
      links: [],
    },
    {
      id: "puzi-medical",
      title: "朴子醫療地景",
      description: "請在這裡補上主題簡介。",
      coverImage: "public/images/themes/puzi-medical/cover.jpg",
      gallery: [],
      documents: [],
      links: [],
    },
    {
      id: "embroidery",
      title: "刺繡文化",
      description: "請在這裡補上主題簡介。",
      coverImage: "public/images/themes/embroidery/cover.jpg",
      gallery: [],
      documents: [],
      links: [],
    },
    {
      id: "coastal",
      title: "海區地方創生",
      description: "請在這裡補上主題簡介。",
      coverImage: "public/images/themes/coastal/cover.jpg",
      gallery: [],
      documents: [],
      links: [],
    },
    {
      id: "food-agri",
      title: "食農教育與地方產業",
      description: "請在這裡補上主題簡介。",
      coverImage: "public/images/themes/food-agri/cover.jpg",
      gallery: [],
      documents: [],
      links: [],
    },
  ],

  digitalTours: [
    {
      id: "chilan-game",
      title: "赤蘭溪闖關遊戲",
      description: "請在這裡補上互動內容簡介。",
      coverImage: "public/images/digital/chilan-game/cover.jpg",
      url: "https://cycc-yimi.github.io/grandma-memory-box/",
      gallery: [],
      documents: [],
    },
    {
      id: "chilan-walk",
      title: "赤蘭溪走讀",
      description: "請在這裡補上走讀路線或站點簡介。",
      coverImage: "public/images/digital/chilan-walk/cover.jpg",
      gallery: [],
      documents: [],
      routeStops: [],
    },
    {
      id: "early-life",
      title: "赤蘭溪早年生活型態",
      description: "請在這裡補上 Podcast 或語音導覽總介紹。",
      coverImage: "public/images/digital/early-life/cover.jpg",
      gallery: [],
      podcastEpisodes: [
        {
          title: "赤蘭溪早年生活故事一",
          description: "請補上單集簡介。",
          image: "public/images/digital/early-life/episode-01.jpg",
          audio: "public/audio/digital/early-life/episode-01.mp3",
        },
      ],
      documents: [],
    },
    {
      id: "puzi-medical-walk",
      title: "朴子醫療走讀",
      description: "請在這裡補上走讀路線或站點簡介。",
      coverImage: "public/images/digital/puzi-medical-walk/cover.jpg",
      gallery: [],
      documents: [],
      routeStops: [],
    },
  ],

  clubs: [
    {
      id: "wood-repair",
      title: "嘉邑木工修繕社",
      description: "請在這裡補上社團簡介。",
      coverImage: "public/images/clubs/wood-repair/cover.jpg",
      gallery: [],
      documents: [],
      links: [],
    },
    {
      id: "saxophone",
      title: "薩克斯風社",
      description: "請在這裡補上社團簡介。",
      coverImage: "public/images/clubs/saxophone/cover.jpg",
      gallery: [],
      documents: [],
      links: [],
    },
    {
      id: "dance",
      title: "多元舞蹈社",
      description: "請在這裡補上社團簡介。",
      coverImage: "public/images/clubs/dance/cover.jpg",
      gallery: [],
      documents: [],
      links: [],
    },
    {
      id: "enka",
      title: "日本演歌說唱社",
      description: "請在這裡補上社團簡介。",
      coverImage: "public/images/clubs/enka/cover.jpg",
      gallery: [],
      documents: [],
      links: [],
    },
    {
      id: "qigong",
      title: "太極十八式氣功暨身心調理社",
      description: "請在這裡補上社團簡介。",
      coverImage: "public/images/clubs/qigong/cover.jpg",
      gallery: [],
      documents: [],
      links: [],
    },
    {
      id: "sketch",
      title: "嘉憶速寫社",
      description: "請在這裡補上社團簡介。",
      coverImage: "public/images/clubs/sketch/cover.jpg",
      gallery: [],
      documents: [],
      links: [],
    },
  ],
};
