import { createRef } from "react";
import { cleanup, render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import { DraftMediaEditor, type DraftMediaEditorHandle } from "./DraftMediaEditor";

const mocks=vi.hoisted(()=>({getMediaForContent:vi.fn(),removeDraftMedia:vi.fn(),cleanupDraftMedia:vi.fn(),uploadDraftMedia:vi.fn()}));
vi.mock("../../data/media-repository",async(importOriginal)=>({...await importOriginal<typeof import("../../data/media-repository")>(),...mocks}));
const legacy={id:"legacy-row",referenceId:"CR-115-039:cover",contentId:"content",draftId:null,source:"github_legacy",role:"cover",legacyPath:"public/images/test.jpg",bucket:null,objectPath:null,originalFilename:"legacy.jpg",mimeType:"image/jpeg",byteSize:1,width:640,height:480,checksumSha256:"a".repeat(64),altText:"既有替代文字",containsPortrait:"unknown",rightsStatus:"unknown",previewUrl:"https://example.test/legacy.jpg"};
const draft={...legacy,id:"44444444-4444-4444-8444-444444444444",referenceId:"44444444-4444-4444-8444-444444444444",draftId:"draft",source:"cms_draft",role:"gallery",legacyPath:null,bucket:"cms-drafts",objectPath:"owner/content/media/media.png",originalFilename:"draft.png",altText:"",previewUrl:"https://signed.test/image"};
const props={client:{} as never,contentId:"content",draftId:"draft",coverAssetId:legacy.referenceId,galleryAssetIds:[draft.referenceId],onReferences:vi.fn(),onDirty:vi.fn(),onUploading:vi.fn()};
beforeEach(()=>{vi.clearAllMocks();mocks.getMediaForContent.mockResolvedValue([legacy,draft]);mocks.removeDraftMedia.mockResolvedValue(undefined);mocks.cleanupDraftMedia.mockResolvedValue(undefined);});
afterEach(cleanup);

test("既有圖片顯示公開來源badge、metadata唯讀且解除引用不刪row",async()=>{render(<DraftMediaEditor {...props}/>);expect(await screen.findByText("既有公開圖片")).toBeInTheDocument();expect(screen.queryByText("Legacy")).not.toBeInTheDocument();expect(screen.queryByText("github_legacy")).not.toBeInTheDocument();expect(screen.getByDisplayValue("既有替代文字")).toBeDisabled();await userEvent.click(screen.getByRole("button",{name:"從草稿移除"}));expect(props.onReferences).toHaveBeenCalledWith(null,[draft.referenceId]);expect(mocks.removeDraftMedia).not.toHaveBeenCalled();});
test("草稿metadata、排序、刪除於儲存後執行",async()=>{vi.spyOn(window,"confirm").mockReturnValue(true);const ref=createRef<DraftMediaEditorHandle>();render(<DraftMediaEditor ref={ref}{...props}/>);await screen.findByText("草稿圖片");const alt=screen.getAllByLabelText("替代文字").find((field)=>!(field as HTMLInputElement).disabled)!;await userEvent.type(alt,"相簿替代文字");expect(ref.current?.metadata()[0]).toMatchObject({id:draft.id,altText:"相簿替代文字"});await userEvent.click(screen.getByRole("button",{name:"移除草稿圖片"}));expect(mocks.removeDraftMedia).not.toHaveBeenCalled();await ref.current?.afterSave();expect(mocks.removeDraftMedia).toHaveBeenCalledWith({},expect.objectContaining({id:draft.id}));});
test("gallery多圖input逐張上傳並回報partial狀態",async()=>{mocks.uploadDraftMedia.mockResolvedValueOnce({asset:{...draft,id:"new-one",referenceId:"new-one"},warnings:[]}).mockRejectedValueOnce(new Error("MEDIA_HEADER_MISMATCH"));render(<DraftMediaEditor {...props}/>);await screen.findByText("草稿圖片");const input=screen.getByLabelText("新增圖片");await userEvent.upload(input,[new File(["one"],"one.png",{type:"image/png"}),new File(["two"],"two.jpg",{type:"image/jpeg"})]);await waitFor(()=>expect(mocks.uploadDraftMedia).toHaveBeenCalledTimes(2));expect(await screen.findByText(/two.jpg：圖片內容與檔案格式不一致/)).toBeInTheDocument();});
