import { createRef } from "react";
import { cleanup, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import { DraftMediaEditor, type DraftMediaEditorHandle } from "./DraftMediaEditor";

const mocks=vi.hoisted(()=>({getMediaForContent:vi.fn(),removeDraftMedia:vi.fn(),cleanupDraftMedia:vi.fn(),uploadDraftMedia:vi.fn(),createDerivedMediaVersion:vi.fn(),restoreOriginalMedia:vi.fn()}));
vi.mock("../../data/media-repository",async(importOriginal)=>({...await importOriginal<typeof import("../../data/media-repository")>(),...mocks}));
const legacy={id:"legacy-row",referenceId:"CR-115-039:cover",contentId:"content",draftId:null,source:"github_legacy",role:"cover",legacyPath:"public/images/test.jpg",bucket:null,objectPath:null,originalFilename:"legacy.jpg",mimeType:"image/jpeg",byteSize:1,width:640,height:480,checksumSha256:"a".repeat(64),altText:"既有替代文字",containsPortrait:"unknown",rightsStatus:"unknown",originalMediaId:null,transformation:null,previewUrl:"https://example.test/legacy.jpg"};
const draft={...legacy,id:"44444444-4444-4444-8444-444444444444",referenceId:"44444444-4444-4444-8444-444444444444",draftId:"draft",source:"cms_draft",role:"gallery",legacyPath:null,bucket:"cms-drafts",objectPath:"owner/content/media/media.png",originalFilename:"draft.png",altText:"",previewUrl:"https://signed.test/image"};
const props={client:{} as never,contentId:"content",draftId:"draft",coverAssetId:legacy.referenceId,galleryAssetIds:[draft.referenceId],onReferences:vi.fn(),onDirty:vi.fn(),onUploading:vi.fn(),onEditing:vi.fn(),onVersionSaved:vi.fn()};
beforeEach(()=>{vi.clearAllMocks();mocks.getMediaForContent.mockResolvedValue([legacy,draft]);mocks.removeDraftMedia.mockResolvedValue(undefined);mocks.cleanupDraftMedia.mockResolvedValue(undefined);});
afterEach(cleanup);

test("既有圖片顯示公開來源badge、metadata唯讀且解除引用不刪row",async()=>{render(<DraftMediaEditor {...props}/>);expect(await screen.findByText("既有公開圖片")).toBeInTheDocument();expect(screen.queryByText("Legacy")).not.toBeInTheDocument();expect(screen.queryByText("github_legacy")).not.toBeInTheDocument();expect(screen.getByDisplayValue("既有替代文字")).toBeDisabled();await userEvent.click(screen.getByRole("button",{name:"從草稿移除"}));expect(props.onReferences).toHaveBeenCalledWith(null,[draft.referenceId]);expect(mocks.removeDraftMedia).not.toHaveBeenCalled();});
test("Legacy卡片不提供編輯或恢復原圖",async()=>{render(<DraftMediaEditor {...props}/>);const legacyCard=(await screen.findByText("既有公開圖片")).closest("article")!;expect(within(legacyCard).getByText("既有公開圖片目前不可直接編輯。")).toBeInTheDocument();expect(within(legacyCard).queryByRole("button",{name:"編輯圖片"})).not.toBeInTheDocument();expect(within(legacyCard).queryByRole("button",{name:"恢復原圖"})).not.toBeInTheDocument();});
test("草稿metadata、排序、刪除於儲存後執行",async()=>{vi.spyOn(window,"confirm").mockReturnValue(true);const ref=createRef<DraftMediaEditorHandle>();render(<DraftMediaEditor ref={ref}{...props}/>);await screen.findByText("草稿圖片");const alt=screen.getAllByLabelText("替代文字").find((field)=>!(field as HTMLInputElement).disabled)!;await userEvent.type(alt,"相簿替代文字");expect(ref.current?.metadata()[0]).toMatchObject({id:draft.id,altText:"相簿替代文字"});await userEvent.click(screen.getByRole("button",{name:"移除草稿圖片"}));expect(mocks.removeDraftMedia).not.toHaveBeenCalled();await ref.current?.afterSave();expect(mocks.removeDraftMedia).toHaveBeenCalledWith({},expect.objectContaining({id:draft.id}));});
test("gallery多圖input逐張上傳、立即保存reference並回報partial狀態",async()=>{mocks.uploadDraftMedia.mockResolvedValueOnce({asset:{...draft,id:"new-one",referenceId:"new-one"},draft:{revision:3,status:"draft",updatedAt:"2026-08-28T00:00:00Z"},warnings:[],reattached:false}).mockRejectedValueOnce(new Error("MEDIA_HEADER_MISMATCH"));render(<DraftMediaEditor {...props}/>);await screen.findByText("草稿圖片");const input=screen.getByLabelText("新增圖片");await userEvent.upload(input,[new File(["one"],"one.png",{type:"image/png"}),new File(["two"],"two.jpg",{type:"image/jpeg"})]);await waitFor(()=>expect(mocks.uploadDraftMedia).toHaveBeenCalledTimes(2));expect(props.onVersionSaved).toHaveBeenCalledWith(legacy.referenceId,[draft.referenceId,"new-one"],expect.objectContaining({revision:3}));expect(await screen.findByText(/one.png：已上傳並儲存至草稿/)).toBeInTheDocument();expect(await screen.findByText(/two.jpg：圖片內容與檔案格式不一致/)).toBeInTheDocument();});
test("duplicate未引用圖片reattach時沿用既有asset並回報revision",async()=>{const orphan={...draft,id:"orphan",referenceId:"orphan",role:"cover"};mocks.getMediaForContent.mockResolvedValue([orphan]);mocks.uploadDraftMedia.mockResolvedValue({asset:orphan,draft:{revision:4,status:"draft",updatedAt:"2026-08-28T00:01:00Z"},warnings:[],reattached:true});render(<DraftMediaEditor {...props} coverAssetId={null} galleryAssetIds={[]}/>);await screen.findByText("尚未設定封面。");await userEvent.upload(screen.getByLabelText("上傳封面"),new File(["same"],"same.jpg",{type:"image/jpeg"}));expect(await screen.findByText(/已恢復既有圖片/)).toBeInTheDocument();expect(props.onVersionSaved).toHaveBeenCalledWith("orphan",[],expect.objectContaining({revision:4}));});
test("duplicate已attach顯示已在此草稿中",async()=>{const attached={...draft,id:"attached",referenceId:"attached",role:"cover"};mocks.getMediaForContent.mockResolvedValue([attached]);mocks.uploadDraftMedia.mockRejectedValue(new Error("MEDIA_ALREADY_ATTACHED"));render(<DraftMediaEditor {...props} coverAssetId="attached" galleryAssetIds={[]}/>);await screen.findByText("草稿圖片");await userEvent.upload(screen.getByLabelText("替換封面"),new File(["same"],"same.jpg",{type:"image/jpeg"}));expect(await screen.findByText(/這張圖片已經在此草稿中/)).toBeInTheDocument();});
test("已編輯Gallery恢復原圖時維持位置並回報revision",async()=>{vi.spyOn(window,"confirm").mockReturnValue(true);const root={...draft,id:"root",referenceId:"root",objectPath:"owner/content/root/root.png"};const edited={...draft,id:"edited",referenceId:"edited",objectPath:"owner/content/edited/edited.png",originalMediaId:"root",transformation:{rotation:90,crop:{x:0,y:0,width:1,height:1,aspectRatio:"original"},normalizedOrientation:true,originalOrientation:1}};mocks.getMediaForContent.mockResolvedValue([legacy,root,edited]);mocks.restoreOriginalMedia.mockResolvedValue({original:root,draft:{revision:7,status:"draft",updatedAt:"2026-08-27T01:00:00Z"}});render(<DraftMediaEditor {...props} galleryAssetIds={["before",edited.referenceId,"after"]}/>);const badge=await screen.findByText("已編輯");const card=badge.closest("article")!;await userEvent.click(within(card).getByRole("button",{name:"恢復原圖"}));await waitFor(()=>expect(mocks.restoreOriginalMedia).toHaveBeenCalled());expect(props.onReferences).toHaveBeenCalledWith(legacy.referenceId,["before",root.referenceId,"after"]);expect(props.onVersionSaved).toHaveBeenCalledWith(legacy.referenceId,["before",root.referenceId,"after"],expect.objectContaining({revision:7,status:"draft"}));});
