import { createRef } from "react";
import { cleanup, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import { batchCapacity, DraftMediaEditor, MAX_BATCH_FILES, reorderGallery, type DraftMediaEditorHandle } from "./DraftMediaEditor";

const mocks=vi.hoisted(()=>({getMediaForContent:vi.fn(),removeDraftMedia:vi.fn(),cleanupDraftMedia:vi.fn(),uploadDraftMedia:vi.fn(),createDerivedMediaVersion:vi.fn(),restoreOriginalMedia:vi.fn()}));
vi.mock("../../data/media-repository",async(importOriginal)=>({...await importOriginal<typeof import("../../data/media-repository")>(),...mocks}));
const legacy={id:"legacy-row",referenceId:"CR-115-039:cover",contentId:"content",draftId:null,source:"github_legacy",role:"cover",legacyPath:"public/images/test.jpg",bucket:null,objectPath:null,originalFilename:"legacy.jpg",mimeType:"image/jpeg",byteSize:1,width:640,height:480,checksumSha256:"a".repeat(64),altText:"既有替代文字",containsPortrait:"unknown",rightsStatus:"unknown",originalMediaId:null,transformation:null,previewUrl:"https://example.test/legacy.jpg"};
const draft={...legacy,id:"44444444-4444-4444-8444-444444444444",referenceId:"44444444-4444-4444-8444-444444444444",draftId:"draft",source:"cms_draft",role:"gallery",legacyPath:null,bucket:"cms-drafts",objectPath:"owner/content/media/media.png",originalFilename:"draft.png",altText:"",previewUrl:"https://signed.test/image"};
const props={client:{} as never,contentId:"content",draftId:"draft",coverAssetId:legacy.referenceId,galleryAssetIds:[draft.referenceId],onReferences:vi.fn(),onDirty:vi.fn(),onUploading:vi.fn(),onEditing:vi.fn(),onVersionSaved:vi.fn()};
beforeEach(()=>{vi.clearAllMocks();mocks.getMediaForContent.mockResolvedValue([legacy,draft]);mocks.removeDraftMedia.mockResolvedValue(undefined);mocks.cleanupDraftMedia.mockResolvedValue(undefined);});
afterEach(cleanup);

test("altText欄位名稱、help、必填訊息與批次說明使用統一文案",async()=>{
  const ref=createRef<DraftMediaEditorHandle>();
  render(<DraftMediaEditor {...props} ref={ref}/>);
  const fields=await screen.findAllByRole("textbox",{name:"圖片替代文字（網站不顯示）"});
  expect(fields).toHaveLength(2);
  expect(screen.getAllByText("供無障礙閱讀與圖片載入失敗時使用，請簡短描述照片內容。")).toHaveLength(2);
  const editable=fields.find(field=>!field.hasAttribute("disabled"))!;
  expect(editable).toHaveAccessibleDescription("供無障礙閱讀與圖片載入失敗時使用，請簡短描述照片內容。 請填寫圖片替代文字");
  expect(ref.current?.warnings()).toContainEqual(expect.objectContaining({code:"media.altMissing",message:"請填寫圖片替代文字"}));
  expect(ref.current?.metadata()[0]).toHaveProperty("altText","");
  expect(screen.getByText("單次最多上傳10張，相簿最多20張")).toBeInTheDocument();
  expect(screen.queryByText("圖片說明",{exact:true})).not.toBeInTheDocument();
});

test("既有圖片顯示公開來源badge、metadata唯讀且解除引用不刪row",async()=>{render(<DraftMediaEditor {...props}/>);expect(await screen.findByText("既有公開圖片")).toBeInTheDocument();expect(screen.queryByText("Legacy")).not.toBeInTheDocument();expect(screen.queryByText("github_legacy")).not.toBeInTheDocument();expect(screen.getByDisplayValue("既有替代文字")).toBeDisabled();const card=screen.getByText("既有公開圖片").closest("article")!;await userEvent.click(within(card).getByRole("button",{name:"移除"}));expect(props.onReferences).toHaveBeenCalledWith(null,[draft.referenceId]);expect(mocks.removeDraftMedia).not.toHaveBeenCalled();});
test("Legacy卡片不提供旋轉裁切或恢復原圖",async()=>{render(<DraftMediaEditor {...props}/>);const legacyCard=(await screen.findByText("既有公開圖片")).closest("article")!;expect(within(legacyCard).getByText("既有公開圖片目前不可直接編輯。")).toBeInTheDocument();expect(within(legacyCard).queryByRole("button",{name:"旋轉／裁切"})).not.toBeInTheDocument();expect(within(legacyCard).queryByRole("button",{name:"恢復原圖"})).not.toBeInTheDocument();});
test("草稿metadata、排序、刪除於儲存後執行",async()=>{vi.spyOn(window,"confirm").mockReturnValue(true);const ref=createRef<DraftMediaEditorHandle>();render(<DraftMediaEditor ref={ref}{...props}/>);await screen.findByText("草稿圖片");const card=screen.getByText("草稿圖片").closest("article")!;const alt=within(card).getByRole("textbox");await userEvent.type(alt,"相簿替代文字");expect(ref.current?.metadata()[0]).toMatchObject({id:draft.id,altText:"相簿替代文字"});await userEvent.click(within(card).getByRole("button",{name:"移除"}));expect(mocks.removeDraftMedia).not.toHaveBeenCalled();await ref.current?.afterSave();expect(mocks.removeDraftMedia).toHaveBeenCalledWith({},expect.objectContaining({id:draft.id}));});
test("批次選擇需明確開始，partial failure可逐張重試",async()=>{mocks.uploadDraftMedia.mockResolvedValueOnce({asset:{...draft,id:"new-one",referenceId:"new-one"},draft:{revision:3,status:"draft",updatedAt:"2026-08-28T00:00:00Z"},warnings:[],reattached:false}).mockRejectedValueOnce(new Error("MEDIA_HEADER_MISMATCH")).mockResolvedValueOnce({asset:{...draft,id:"new-two",referenceId:"new-two"},draft:{revision:4,status:"draft",updatedAt:"2026-08-28T00:01:00Z"},warnings:[],reattached:false});render(<DraftMediaEditor {...props}/>);await screen.findByText("草稿圖片");const input=screen.getByLabelText("選擇多張圖片");expect(input).toHaveAttribute("multiple");await userEvent.upload(input,[new File(["one"],"one.png",{type:"image/png"}),new File(["two"],"two.jpg",{type:"image/jpeg"})]);expect(mocks.uploadDraftMedia).not.toHaveBeenCalled();await userEvent.click(screen.getByRole("button",{name:"開始上傳"}));await waitFor(()=>expect(mocks.uploadDraftMedia).toHaveBeenCalledTimes(2));expect(screen.getByText(/one.png/)).toBeInTheDocument();expect(screen.getByText(/圖片內容與檔案格式不一致/)).toBeInTheDocument();await userEvent.click(screen.getByRole("button",{name:"重新上傳"}));await waitFor(()=>expect(mocks.uploadDraftMedia).toHaveBeenCalledTimes(3));expect(props.onVersionSaved).toHaveBeenCalled();});

test("一次最多加入10張且無封面時可在上傳前改選封面",async()=>{mocks.getMediaForContent.mockResolvedValue([]);render(<DraftMediaEditor {...props} coverAssetId={null} galleryAssetIds={[]}/>);await screen.findByText("尚未設定封面。");const files=Array.from({length:12},(_,index)=>new File([String(index)],`photo-${index+1}.jpg`,{type:"image/jpeg"}));await userEvent.upload(screen.getByLabelText("選擇多張圖片"),files);expect(screen.getAllByRole("listitem")).toHaveLength(10);expect(screen.getByText(/本次有 2 張未加入/)).toBeInTheDocument();const second=screen.getByText("photo-2.jpg").closest("li")!;await userEvent.click(within(second).getByRole("button",{name:"設為封面"}));expect(within(second).getByText(/封面・等待中/)).toBeInTheDocument();expect(mocks.uploadDraftMedia).not.toHaveBeenCalled();});

test("批次上傳同時最多處理3張並回報離開頁面保護狀態",async()=>{const resolvers:Array<()=>void>=[];let active=0,maxActive=0;const completed=()=>({asset:{...draft,id:crypto.randomUUID(),referenceId:crypto.randomUUID()},draft:{revision:3,status:"draft",updatedAt:"2026-08-28T00:00:00Z"},warnings:[],reattached:false});mocks.uploadDraftMedia.mockImplementation(()=>new Promise((resolve)=>{active+=1;maxActive=Math.max(maxActive,active);resolvers.push(()=>{active-=1;resolve(completed());});}));render(<DraftMediaEditor {...props}/>);await screen.findByText("草稿圖片");const files=Array.from({length:5},(_,index)=>new File([String(index)],`batch-${index}.png`,{type:"image/png"}));await userEvent.upload(screen.getByLabelText("選擇多張圖片"),files);await userEvent.click(screen.getByRole("button",{name:"開始上傳"}));await waitFor(()=>expect(mocks.uploadDraftMedia).toHaveBeenCalledTimes(3));expect(props.onUploading).toHaveBeenLastCalledWith(true);resolvers.shift()?.();await waitFor(()=>expect(mocks.uploadDraftMedia).toHaveBeenCalledTimes(4));while(resolvers.length)resolvers.shift()?.();await waitFor(()=>expect(mocks.uploadDraftMedia).toHaveBeenCalledTimes(5));while(resolvers.length)resolvers.shift()?.();await waitFor(()=>expect(props.onUploading).toHaveBeenLastCalledWith(false));expect(maxActive).toBe(3);});

test("往前按鈕提供拖曳以外的鍵盤排序方式",async()=>{const second={...draft,id:"second",referenceId:"second",originalFilename:"second.png"};mocks.getMediaForContent.mockResolvedValue([legacy,draft,second]);render(<DraftMediaEditor {...props} galleryAssetIds={[draft.referenceId,second.referenceId]}/>);await screen.findByText("second.png");await userEvent.click(screen.getByRole("button",{name:"將相簿 2 往前"}));expect(props.onReferences).toHaveBeenCalledWith(legacy.referenceId,[second.referenceId,draft.referenceId]);});
test("duplicate未引用圖片reattach時沿用既有asset並回報revision",async()=>{const orphan={...draft,id:"orphan",referenceId:"orphan",role:"cover"};mocks.getMediaForContent.mockResolvedValue([orphan]);mocks.uploadDraftMedia.mockResolvedValue({asset:orphan,draft:{revision:4,status:"draft",updatedAt:"2026-08-28T00:01:00Z"},warnings:[],reattached:true});render(<DraftMediaEditor {...props} coverAssetId={null} galleryAssetIds={[]}/>);await screen.findByText("尚未設定封面。");await userEvent.upload(screen.getByLabelText("上傳封面"),new File(["same"],"same.jpg",{type:"image/jpeg"}));expect(await screen.findByText(/已恢復既有圖片/)).toBeInTheDocument();expect(props.onVersionSaved).toHaveBeenCalledWith("orphan",[],expect.objectContaining({revision:4}));});
test("duplicate已attach顯示已在此草稿中",async()=>{const attached={...draft,id:"attached",referenceId:"attached",role:"cover"};mocks.getMediaForContent.mockResolvedValue([attached]);mocks.uploadDraftMedia.mockRejectedValue(new Error("MEDIA_ALREADY_ATTACHED"));render(<DraftMediaEditor {...props} coverAssetId="attached" galleryAssetIds={[]}/>);await screen.findByText("草稿圖片");await userEvent.upload(screen.getByLabelText("替換封面"),new File(["same"],"same.jpg",{type:"image/jpeg"}));expect(await screen.findByText(/此圖片已經在此草稿中/)).toBeInTheDocument();});
test("已編輯Gallery恢復原圖時維持位置並回報revision",async()=>{vi.spyOn(window,"confirm").mockReturnValue(true);const root={...draft,id:"root",referenceId:"root",objectPath:"owner/content/root/root.png"};const edited={...draft,id:"edited",referenceId:"edited",objectPath:"owner/content/edited/edited.png",originalMediaId:"root",transformation:{rotation:90,crop:{x:0,y:0,width:1,height:1,aspectRatio:"original"},normalizedOrientation:true,originalOrientation:1}};mocks.getMediaForContent.mockResolvedValue([legacy,root,edited]);mocks.restoreOriginalMedia.mockResolvedValue({original:root,draft:{revision:7,status:"draft",updatedAt:"2026-08-27T01:00:00Z"}});render(<DraftMediaEditor {...props} galleryAssetIds={["before",edited.referenceId,"after"]}/>);const badge=await screen.findByText("已編輯");const card=badge.closest("article")!;await userEvent.click(within(card).getByRole("button",{name:"恢復原圖"}));await waitFor(()=>expect(mocks.restoreOriginalMedia).toHaveBeenCalled());expect(props.onReferences).toHaveBeenCalledWith(legacy.referenceId,["before",root.referenceId,"after"]);expect(props.onVersionSaved).toHaveBeenCalledWith(legacy.referenceId,["before",root.referenceId,"after"],expect.objectContaining({revision:7,status:"draft"}));});

test("批次容量限制為10張並尊重相簿上限",()=>{expect(MAX_BATCH_FILES).toBe(10);expect(batchCapacity(0,false)).toBe(10);expect(batchCapacity(19,true)).toBe(1);expect(batchCapacity(20,true)).toBe(0);});

test("分次選檔仍計入待上傳佇列，不可累積超過單批容量",async()=>{
  mocks.getMediaForContent.mockResolvedValue([]);
  render(<DraftMediaEditor {...props} coverAssetId={null} galleryAssetIds={[]}/>);
  await screen.findByText("尚未設定封面。");
  const files=(prefix:string)=>Array.from({length:7},(_,i)=>new File([String(i)],`${prefix}-${i}.jpg`,{type:"image/jpeg"}));
  await userEvent.upload(screen.getByLabelText("選擇多張圖片"),files("first"));
  await userEvent.upload(screen.getByLabelText("選擇多張圖片"),files("second"));
  expect(screen.getAllByRole("listitem")).toHaveLength(10);
  expect(screen.getByText(/本次有 4 張未加入/)).toBeInTheDocument();
});
test("相簿排序保持其餘圖片順序且非法索引不改動",()=>{expect(reorderGallery(["a","b","c"],2,0)).toEqual(["c","a","b"]);expect(reorderGallery(["a","b"],-1,0)).toEqual(["a","b"]);});

test("批次設定會套用權利與人物狀態但保留逐張圖片替代文字",async()=>{const ref=createRef<DraftMediaEditorHandle>();render(<DraftMediaEditor ref={ref}{...props}/>);await screen.findByText("草稿圖片");const batch=screen.getByRole("heading",{name:"批次設定"}).closest("div")!;const rights=within(batch).getByLabelText("圖片使用權");const portrait=within(batch).getByLabelText("是否含可辨識人物");await userEvent.selectOptions(rights,"authorized");await userEvent.selectOptions(portrait,"yes");await userEvent.click(within(batch).getByRole("button",{name:"套用到全部圖片"}));expect(ref.current?.metadata()[0]).toMatchObject({id:draft.id,altText:"",rightsStatus:"authorized",containsPortrait:"yes"});expect(screen.getAllByText(/圖片替代文字仍須逐張填寫/).length).toBeGreaterThan(0);});
