import { useEffect, useState } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";
import { fetchGitHubPublication, finalizeGitHubPublication, requestGitHubPublication, type GitHubPublication, type PublicationMediaPreparation, type PublicationSnapshotSummary } from "../../data/publication-repository";
import { publicationLabels as label } from "../../content/publication-ui-state";

interface Props{client:SupabaseClient;snapshot:PublicationSnapshotSummary|null;publicationRecord?:GitHubPublication|null;mediaPreparation:PublicationMediaPreparation|null;currentRevision?:number;blocked?:boolean;allowSubmit?:boolean;onPublicationChange?(publication:GitHubPublication):void}
function message(error:unknown):string{const code=error instanceof Error?error.message:"";if(code==="MAIN_CHANGED")return"網站資料已有新版本，請重新送出發布。";if(code==="PAGES_DEPLOYMENT_PENDING")return"網站仍在更新，請稍後重新檢查。";if(code==="PULL_REQUEST_NOT_MERGED")return"內容尚待管理員確認。";if(code==="ACTIVE_PUBLICATION_EXISTS")return"此內容已有進行中的發布作業。";return"網站發布作業未完成，請稍後再試或聯絡系統管理員。";}

export function GitHubPublicationPanel({client,snapshot,publicationRecord,mediaPreparation,blocked=false,allowSubmit=true,onPublicationChange}:Props){
  const[localPublication,setPublication]=useState<GitHubPublication|null>(null);const[working,setWorking]=useState<string|null>(null);const[error,setError]=useState("");
  const publication=publicationRecord!==undefined?publicationRecord:localPublication;
  const update=(value:GitHubPublication|null)=>{setPublication(value);if(value)onPublicationChange?.(value);};
  useEffect(()=>{let active=true;setPublication(publicationRecord??null);setError("");if(!snapshot||publicationRecord!==undefined)return()=>{active=false;};void fetchGitHubPublication(client,snapshot.id).then((value)=>{if(active)setPublication(value);}).catch(()=>{if(active)setError("無法讀取網站發布狀態。");});return()=>{active=false;};},[client,snapshot,publicationRecord]);
  const request=async(action:"refresh_status"|"cancel"|"finalize")=>{if(!snapshot||blocked||working)return;if(action==="cancel"&&!window.confirm("確定取消本次尚未公開的發布作業？草稿內容會保留。"))return;setWorking(action);setError("");try{update(action==="finalize"?await finalizeGitHubPublication(client,snapshot.id):await requestGitHubPublication(client,snapshot.id,action));}catch(caught){setError(message(caught));}finally{setWorking(null);}};
  const submit=async()=>{if(!snapshot||!allowSubmit||snapshot.schemaVersion!=="1.1"||mediaPreparation?.status!=="ready"||blocked||working)return;if(!window.confirm("送出後將建立網站發布草稿，並等待管理員確認後才會公開。"))return;setWorking("submit");setError("");try{if(publication?.status!=="dry_run_ready"){const dryRun=await requestGitHubPublication(client,snapshot.id,"dry_run");update(dryRun);if(dryRun.status!=="dry_run_ready")throw new Error("PUBLICATION_DRY_RUN_FAILED");}update(await requestGitHubPublication(client,snapshot.id,"create_draft_pr"));}catch(caught){setError(message(caught));}finally{setWorking(null);}};
  const ready=allowSubmit&&snapshot?.schemaVersion==="1.1"&&mediaPreparation?.status==="ready";const status=publication?.status;const finalized=status==="finalized";
  return <section className="publication-submit" aria-labelledby="publication-submit-title"><div className="publication-panel__heading"><div><h3 id="publication-submit-title">送出網站發布</h3><p className="muted">系統會先檢查正式資料，再建立待確認的網站更新。</p></div><span className="record-status">{status?label[status]??"處理中":"尚未送出"}</span></div>
    {!ready&&!status&&<p className="muted">完成「準備發布」後即可送出。</p>}{error&&<div className="form-error" role="alert">{error}</div>}
    {publication&&<div className="publication-result" aria-live="polite"><strong>{label[publication.status]??"發布處理中"}</strong>{finalized?<span>正式版本 r{snapshot?.revision}</span>:<span>公開前仍須由管理員確認。</span>}{publication.beforeCounts&&publication.afterCounts&&<span>班級 {publication.beforeCounts.classResults} → {publication.afterCounts.classResults}・活動 {publication.beforeCounts.activities} → {publication.afterCounts.activities}</span>}</div>}
    <div className="heading-actions">{(!status||status==="dry_run_ready")&&<button className="button button--accent" type="button" disabled={blocked||!ready||Boolean(working)} onClick={()=>void submit()}>{working?"送出中…":"送出網站發布"}</button>}{status&&["open","merged","deploy_pending"].includes(status)&&<button className="button button--secondary" type="button" disabled={blocked||Boolean(working)} onClick={()=>void request("refresh_status")}>重新檢查發布狀態</button>}{status==="deployed"&&<button className="button button--accent" type="button" disabled={blocked||Boolean(working)} onClick={()=>void request("finalize")}>確認公開並完成發布</button>}{status&&["dry_run_ready","branch_created","open","failed"].includes(status)&&<button className="button button--secondary" type="button" disabled={blocked||Boolean(working)} onClick={()=>void request("cancel")}>取消本次發布</button>}</div>
    {finalized&&publication?.finalizedAt&&<p>發布完成時間 {new Date(publication.finalizedAt).toLocaleString("zh-TW")}</p>}
    <small className="muted">系統不會自動公開；仍保留管理員人工確認。</small>
    {publication&&<details className="publication-advanced"><summary>進階資訊</summary><dl><div><dt>發布狀態</dt><dd>{publication.status}</dd></div><div><dt>變更檔案</dt><dd>{publication.changedFiles.length}</dd></div></dl>{publication.prUrl&&<a href={publication.prUrl} target="_blank" rel="noreferrer">前往 GitHub 檢查</a>}</details>}
  </section>;
}
