import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from "react";
import type { DraftMediaAsset } from "../../data/media-repository";
import { calculateCrop, clampCrop, normalizeRotation, renderEditorCanvas, resizeCrop, transformRenderedCanvas, type CropAspect, type ExifOrientation, type ImageRotation, type NormalizedCrop, type TransformationMetadata } from "../../media/image-editing";

interface Props {
  asset:DraftMediaAsset;
  onCancel():void;
  onDirtyState(value:boolean):void;
  onSave(file:File,metadata:TransformationMetadata):Promise<void>;
}

type Drag={mode:"move"|"resize";x:number;y:number;crop:NormalizedCrop}|null;
const messages:Record<string,[string,string]>={IMAGE_EDITOR_TOO_LARGE:["圖片尺寸過大，暫時無法在瀏覽器中編輯。","canvas.memory"],IMAGE_DECODE_FAILED:["圖片解碼失敗，請重新嘗試。","createImageBitmap"],CANVAS_CONTEXT_UNAVAILABLE:["圖片處理失敗，請重新嘗試。","canvas.getContext"],INVALID_CROP:["裁切範圍無效，請重新調整。","crop.validate"],INVALID_CROP_DIMENSIONS:["裁切後尺寸無效，請重新調整。","crop.dimensions"],IMAGE_ENCODE_FAILED:["圖片編碼失敗，請重新嘗試。","canvas.toBlob"],IMAGE_FORMAT_UNSUPPORTED:["目前瀏覽器無法維持這個圖片格式。","canvas.toBlob.mime"],MEDIA_TYPE_UNSUPPORTED:["目前不支援這個圖片格式。","media.outputOptions"],MEDIA_UPLOAD_FAILED:["新版本上傳失敗，請重新嘗試。","storage.upload"],MEDIA_SERVER_VALIDATION_FAILED:["新版本未通過伺服器驗證。","validate-media-upload"],MEDIA_DUPLICATE:["此圖片版本與既有圖片相同。","validate-media-upload"],DRAFT_MEDIA_ATTACH_FAILED:["新版本已清理，但草稿參照更新失敗。","attach_derived_draft_media"]};
const message=(code:string)=>{const safe=/^[A-Z0-9_-]+(?:__[A-Z0-9_-]+)*$/.test(code)?code:"IMAGE_EDIT_FAILED",base=safe.split("__")[0],entry=messages[base]??["圖片處理失敗，請重新嘗試。","image-edit.save"];return`${entry[0]}（診斷碼：${safe}；步驟：${entry[1]}）`;};

export function ImageEditorModal({asset,onCancel,onDirtyState,onSave}:Props){
  const [blob,setBlob]=useState<Blob|null>(null),[rotation,setRotation]=useState<ImageRotation>(0),[crop,setCrop]=useState<NormalizedCrop>({x:0,y:0,width:1,height:1,aspectRatio:"original"});
  const [dimensions,setDimensions]=useState({width:1,height:1}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[dirty,setDirty]=useState(false);
  const canvasRef=useRef<HTMLCanvasElement>(null),frameRef=useRef<HTMLDivElement>(null),dragRef=useRef<Drag>(null),orientationRef=useRef<ExifOrientation>(1);
  useEffect(()=>{let active=true;if(!asset.previewUrl){setError("圖片暫時無法載入。");setLoading(false);return;}void fetch(asset.previewUrl).then((response)=>{if(!response.ok)throw new Error();return response.blob();}).then((value)=>{if(active)setBlob(value);}).catch(()=>{if(active){setError("圖片暫時無法載入。");setLoading(false);}});return()=>{active=false;};},[asset.previewUrl]);
  useEffect(()=>{let active=true;if(!blob)return;setLoading(true);void renderEditorCanvas(blob,rotation).then(({canvas,orientation})=>{if(!active){canvas.width=0;canvas.height=0;return;}const target=canvasRef.current;if(!target){canvas.width=0;canvas.height=0;return;}const width=canvas.width,height=canvas.height;target.width=width;target.height=height;target.getContext("2d")?.drawImage(canvas,0,0);canvas.width=0;canvas.height=0;orientationRef.current=orientation;setDimensions({width,height});setCrop((current)=>calculateCrop(width,height,current.aspectRatio));setLoading(false);}).catch((cause)=>{if(active){setError(message(cause instanceof Error?cause.message:""));setLoading(false);}});return()=>{active=false;};},[blob,rotation]);
  useEffect(()=>{onDirtyState(dirty);return()=>onDirtyState(false);},[dirty,onDirtyState]);
  const changeRotation=(amount:number)=>{setRotation((current)=>normalizeRotation(current+amount));setDirty(true);};
  const changeAspect=(aspectRatio:CropAspect)=>{setCrop(calculateCrop(dimensions.width,dimensions.height,aspectRatio));setDirty(true);};
  const reset=()=>{setRotation(0);setCrop(calculateCrop(dimensions.width,dimensions.height,"original"));setDirty(false);setError("");};
  const cancel=()=>{if(dirty&&!window.confirm("尚有未儲存的圖片編輯，確定要取消嗎？"))return;onCancel();};
  const begin=(event:ReactPointerEvent,mode:"move"|"resize")=>{event.preventDefault();event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);dragRef.current={mode,x:event.clientX,y:event.clientY,crop};};
  const move=(event:ReactPointerEvent)=>{const drag=dragRef.current,frame=frameRef.current;if(!drag||!frame)return;const box=frame.getBoundingClientRect(),dx=(event.clientX-drag.x)/box.width,dy=(event.clientY-drag.y)/box.height;if(drag.mode==="move")setCrop(clampCrop({...drag.crop,x:drag.crop.x+dx,y:drag.crop.y+dy}));else setCrop(resizeCrop(drag.crop,dimensions.width,dimensions.height,drag.crop.width+dx,drag.crop.height+dy));setDirty(true);};
  const finish=()=>{dragRef.current=null;};
  const save=async()=>{const preview=canvasRef.current;if(!blob||!preview||saving)return;setSaving(true);setError("");try{const transformed=await transformRenderedCanvas(preview,asset.originalFilename,blob.type,rotation,crop,orientationRef.current);await onSave(transformed.file,transformed.metadata);onDirtyState(false);}catch(cause){setError(message(cause instanceof Error?cause.message:""));setSaving(false);}};
  return <div className="image-editor-modal" role="dialog" aria-modal="true" aria-labelledby="image-editor-title"><div className="image-editor-modal__panel"><div className="image-editor-modal__heading"><div><p className="eyebrow">Draft image editor</p><h2 id="image-editor-title">編輯圖片</h2><p className="muted">原始草稿圖片會完整保留。</p></div><button type="button" className="button button--ghost" disabled={saving} onClick={cancel}>關閉</button></div>
    <div className="image-editor-layout"><div className="image-editor__stage" ref={frameRef} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish}><canvas ref={canvasRef} aria-label="圖片編輯預覽" />{!loading&&!error&&<div className="image-editor__crop" style={{left:`${crop.x*100}%`,top:`${crop.y*100}%`,width:`${crop.width*100}%`,height:`${crop.height*100}%`}} onPointerDown={(event)=>begin(event,"move")}><span className="image-editor__handle" aria-hidden="true" onPointerDown={(event)=>begin(event,"resize")} /></div>}{loading&&<div className="image-editor__overlay">正在載入圖片…</div>}</div>
      <aside className="image-editor-controls"><fieldset><legend>旋轉</legend><div className="button-row"><button type="button" className="button button--secondary" onClick={()=>changeRotation(-90)}>向左旋轉</button><button type="button" className="button button--secondary" onClick={()=>changeRotation(90)}>向右旋轉</button><button type="button" className="button button--secondary" onClick={()=>changeRotation(180)}>旋轉180°</button></div></fieldset><label>裁切比例<select value={crop.aspectRatio} onChange={(event)=>changeAspect(event.target.value as CropAspect)}><option value="original">原始比例</option><option value="free">自由裁切</option><option value="4:3">4:3</option><option value="3:4">3:4</option><option value="16:9">16:9</option><option value="1:1">1:1</option></select></label><p className="muted">拖曳裁切框移動位置，拖曳右下角調整大小。</p><dl className="image-editor-summary"><div><dt>旋轉</dt><dd>{rotation}°</dd></div><div><dt>裁切</dt><dd>{crop.aspectRatio}</dd></div></dl></aside></div>
    {error&&<p className="form-error" role="alert">{error}</p>}<div className="image-editor-modal__actions"><button type="button" className="button button--ghost" disabled={saving} onClick={reset}>重設編輯</button><button type="button" className="button button--ghost" disabled={saving} onClick={cancel}>取消</button><button type="button" className="button button--accent" disabled={saving||loading||Boolean(error)} onClick={()=>void save()}>{saving?"正在儲存圖片…":"儲存新版本"}</button></div></div></div>;
}
