import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, expect, test, vi } from "vitest";
import { PublicationMediaPreparationPanel } from "./PublicationMediaPreparationPanel";

const mocks=vi.hoisted(()=>({fetch:vi.fn(),request:vi.fn(),fetchGitHub:vi.fn(),requestGitHub:vi.fn(),finalizeGitHub:vi.fn()}));
vi.mock("../../data/publication-repository",()=>({fetchPublicationMediaPreparation:mocks.fetch,requestPublicationMediaPreparation:mocks.request,fetchGitHubPublication:mocks.fetchGitHub,requestGitHubPublication:mocks.requestGitHub,finalizeGitHubPublication:mocks.finalizeGitHub}));
const client={} as never;
const snapshot={id:"11111111-1111-4111-8111-111111111111",revision:9,schemaVersion:"1.1",checksum:"a".repeat(64),status:"ready",createdAt:"2026-09-02T00:00:00Z"};
const ready={status:"ready",requiredCount:3,promotedCount:3,legacyCount:0,failedCount:0,manifestChecksum:"b".repeat(64),errorCode:null} as const;
afterEach(()=>cleanup());
beforeEach(()=>{mocks.fetch.mockReset();mocks.request.mockReset();mocks.fetchGitHub.mockReset();mocks.requestGitHub.mockReset();mocks.finalizeGitHub.mockReset();mocks.fetch.mockResolvedValue(null);mocks.fetchGitHub.mockResolvedValue(null);});

test("沒有snapshot時按鈕停用",()=>{render(<PublicationMediaPreparationPanel client={client} snapshot={null} currentRevision={9}/>);expect(screen.getByRole("button",{name:"準備正式圖片"})).toBeDisabled();expect(screen.getByText(/請先建立發布快照/)).toBeInTheDocument();});
test("1.1 snapshot但沒有preparation row時顯示尚未準備",async()=>{render(<PublicationMediaPreparationPanel client={client} snapshot={snapshot} currentRevision={9}/>);expect(await screen.findByText("尚未準備")).toBeInTheDocument();expect(screen.getByRole("button",{name:"準備正式圖片"})).toBeEnabled();});
test("1.0 baseline snapshot不可直接準備",async()=>{render(<PublicationMediaPreparationPanel client={client} snapshot={{...snapshot,schemaVersion:"1.0"}} currentRevision={9}/>);expect(await screen.findByText(/舊版發布快照不能直接/)).toBeInTheDocument();expect(screen.getByRole("button",{name:"準備正式圖片"})).toBeDisabled();});
test("確認後準備三張且明示尚未公開",async()=>{mocks.request.mockResolvedValue(ready);const confirm=vi.spyOn(window,"confirm").mockReturnValue(true);render(<PublicationMediaPreparationPanel client={client} snapshot={snapshot} currentRevision={9}/>);const button=await screen.findByRole("button",{name:"準備正式圖片"});fireEvent.click(button);await waitFor(()=>expect(mocks.request).toHaveBeenCalledWith(client,snapshot.id));expect(screen.getAllByText("正式圖片準備完成").length).toBeGreaterThan(0);expect(screen.getByText("需要準備：3・成功：3・既有公開圖片：0")).toBeInTheDocument();expect(screen.getByText("尚未公開")).toBeInTheDocument();expect(confirm.mock.calls[0][0]).toContain("不會更新公開網站");confirm.mockRestore();});
test("all Legacy可直接ready且不顯示技術來源詞",async()=>{mocks.fetch.mockResolvedValue({...ready,requiredCount:0,promotedCount:0,legacyCount:2});render(<PublicationMediaPreparationPanel client={client} snapshot={snapshot} currentRevision={9}/>);expect(await screen.findByText("需要準備：0・成功：0・既有公開圖片：2")).toBeInTheDocument();expect(document.body.textContent).not.toMatch(/cms_draft|cms_public|github_legacy|promotion/i);});
test("reload由DB恢復ready且不可重複執行",async()=>{mocks.fetch.mockResolvedValue(ready);render(<PublicationMediaPreparationPanel client={client} snapshot={snapshot} currentRevision={9}/>);expect(await screen.findByRole("button",{name:"正式圖片準備完成"})).toBeDisabled();expect(mocks.request).not.toHaveBeenCalled();});
test("失敗狀態提供重新嘗試且不顯示raw error",async()=>{mocks.fetch.mockResolvedValue({...ready,status:"failed",promotedCount:1,failedCount:1,errorCode:"SOURCE_OBJECT_MISSING"});mocks.request.mockResolvedValue(ready);vi.spyOn(window,"confirm").mockReturnValue(true);render(<PublicationMediaPreparationPanel client={client} snapshot={snapshot} currentRevision={9}/>);const retry=await screen.findByRole("button",{name:"重新嘗試"});expect(screen.getByText("正式圖片準備未完成")).toBeInTheDocument();expect(screen.queryByText("SOURCE_OBJECT_MISSING")).not.toBeInTheDocument();fireEvent.click(retry);await waitFor(()=>expect(mocks.request).toHaveBeenCalledTimes(1));vi.restoreAllMocks();});
test("preparing與缺少counts的合法初始狀態不會crash",async()=>{mocks.fetch.mockResolvedValue({status:"preparing"});render(<PublicationMediaPreparationPanel client={client} snapshot={snapshot} currentRevision={9}/>);expect(await screen.findByText("準備中")).toBeInTheDocument();expect(screen.queryByText(/NaN/)).not.toBeInTheDocument();});
test("status query錯誤留在元件內顯示，不觸發全域錯誤",async()=>{mocks.fetch.mockRejectedValue(new Error("PUBLICATION_MEDIA_STATUS_FAILED"));render(<PublicationMediaPreparationPanel client={client} snapshot={snapshot} currentRevision={9}/>);expect(await screen.findByRole("alert")).toHaveTextContent("無法讀取正式圖片準備狀態");expect(screen.getByRole("button",{name:"準備正式圖片"})).toBeEnabled();});
test("舊revision snapshot仍可準備但清楚提示",async()=>{render(<PublicationMediaPreparationPanel client={client} snapshot={snapshot} currentRevision={10}/>);expect(await screen.findByText(/不是目前最新草稿版本/)).toBeInTheDocument();expect(screen.getByRole("button",{name:"準備正式圖片"})).toBeEnabled();});
