import { cleanup, fireEvent, render, screen, within } from "@testing-library/react";
import { afterEach, expect, test, vi } from "vitest";
import { WalkingRecordFields, emptyWalkingRecord, walkingTypes } from "./WalkingRecordFields";

const base = { ...emptyWalkingRecord(), summary: "這是一段足夠長度的走讀摘要內容，供測試使用。" };
const renderFields = (value: typeof base | null = base, onChange = vi.fn()) => ({ onChange, ...render(<WalkingRecordFields value={value} activityCoverAssetId="cover-a" galleryAssetIds={["gallery-a", "gallery-b"]} walkingRecordId={null} errorFor={() => undefined} onChange={onChange} />) });
afterEach(() => { cleanup(); vi.restoreAllMocks(); });

test("disabled state is nullable and does not create content", () => {
  const onChange = vi.fn(); renderFields(null, onChange);
  expect(screen.getByText("此活動尚未建立走讀與田野紀錄。")).toBeInTheDocument();
  expect(onChange).not.toHaveBeenCalled();
});
test("toggle on creates only an empty walking contract", () => { const { onChange } = renderFields(null); fireEvent.click(screen.getByRole("checkbox")); expect(onChange).toHaveBeenCalledWith(emptyWalkingRecord()); });
test("toggle off requires exact confirmation and removes walking draft", () => { const confirm = vi.spyOn(window, "confirm").mockReturnValue(true); const { onChange } = renderFields(); fireEvent.click(screen.getByRole("checkbox")); expect(confirm).toHaveBeenCalledWith("取消後，這筆活動的走讀與田野草稿內容將被移除。\n既有 WR ID 不會因此回收。"); expect(onChange).toHaveBeenCalledWith(null); });
test("cancelled disable keeps walking data", () => { vi.spyOn(window, "confirm").mockReturnValue(false); const { onChange } = renderFields(); fireEvent.click(screen.getByRole("checkbox")); expect(onChange).not.toHaveBeenCalled(); });
test("empty just-enabled walking state disables without disruptive confirmation", () => { const confirm = vi.spyOn(window, "confirm"); const onChange = vi.fn(); renderFields(emptyWalkingRecord(), onChange); fireEvent.click(screen.getByRole("checkbox")); expect(confirm).not.toHaveBeenCalled(); expect(onChange).toHaveBeenCalledWith(null); });
test("type selector contains exactly the eight contract values", () => { renderFields(); expect(within(screen.getByLabelText(/走讀／田野類型/)).getAllByRole("option").map((node) => node.textContent)).toEqual(walkingTypes); });
test("summary has independent counter and never copies activity summary", () => { renderFields(); expect(screen.getByText(new RegExp(`已輸入 ${base.summary.length} 字`))).toBeInTheDocument(); expect(screen.getByLabelText(/走讀摘要/)).toHaveValue(base.summary); });
test("WR ID is not fabricated before server allocation", () => { renderFields(); expect(screen.getByText("將於後端建立識別碼")).toBeInTheDocument(); });
test("existing WR ID is read only", () => { render(<WalkingRecordFields value={base} activityCoverAssetId={null} galleryAssetIds={[]} walkingRecordId="WR-115-001" errorFor={() => undefined} onChange={vi.fn()} />); expect(screen.getByText("WR-115-001")).toBeInTheDocument(); expect(screen.queryByDisplayValue("WR-115-001")).not.toBeInTheDocument(); });
test("stop add uses blank name and nullable note", () => { const { onChange } = renderFields(); fireEvent.click(screen.getByRole("button", { name: "＋新增站點" })); expect(onChange).toHaveBeenCalledWith(expect.objectContaining({ stops: [{ name: "", note: null }] })); });
test("stop deletion affects only selected row", () => { const value = { ...base, stops: [{ name: "甲", note: null }, { name: "乙", note: "說明" }] }; const { onChange } = renderFields(value); fireEvent.click(screen.getAllByRole("button", { name: "刪除" })[0]); expect(onChange).toHaveBeenCalledWith(expect.objectContaining({ stops: [{ name: "乙", note: "說明" }] })); });
test("stop order can move down deterministically", () => { const value = { ...base, stops: [{ name: "甲", note: null }, { name: "乙", note: null }] }; const { onChange } = renderFields(value); fireEvent.click(screen.getAllByRole("button", { name: "下移" })[0]); expect(onChange).toHaveBeenCalledWith(expect.objectContaining({ stops: [{ name: "乙", note: null }, { name: "甲", note: null }] })); });
test("field note add is optional and explicit", () => { const { onChange } = renderFields(); fireEvent.click(screen.getByRole("button", { name: "＋新增紀錄" })); expect(onChange).toHaveBeenCalledWith(expect.objectContaining({ fieldNotes: [""] })); });
test("field note deletion affects only selected item", () => { const value = { ...base, fieldNotes: ["甲", "乙"] }; const { onChange } = renderFields(value); fireEvent.click(screen.getAllByRole("button", { name: "刪除" })[0]); expect(onChange).toHaveBeenCalledWith(expect.objectContaining({ fieldNotes: ["乙"] })); });
test("field notes preserve explicit order changes", () => { const value = { ...base, fieldNotes: ["甲", "乙"] }; const { onChange } = renderFields(value); fireEvent.click(screen.getAllByRole("button", { name: "下移" })[0]); expect(onChange).toHaveBeenCalledWith(expect.objectContaining({ fieldNotes: ["乙", "甲"] })); });
test("title override is optional and explains effective title fallback", () => { renderFields(); expect(screen.getByLabelText(/走讀頁標題/)).toHaveValue(""); expect(screen.getByText("留空則沿用活動名稱。")).toBeInTheDocument(); });
test("location override is optional and explains Activity venue fallback", () => { const { onChange } = renderFields(); const input = screen.getByLabelText(/走讀地點顯示/); expect(input).toHaveValue(""); expect(screen.getByText("留空則沿用活動地點；只有走讀頁需要不同的地點描述時才填寫。")).toBeInTheDocument(); fireEvent.change(input, { target: { value: " 三界埔、鹽館 " } }); expect(onChange).toHaveBeenLastCalledWith(expect.objectContaining({ locationOverride: " 三界埔、鹽館 " })); });
test("walking validator error is rendered beside its field", () => { render(<WalkingRecordFields value={base} activityCoverAssetId={null} galleryAssetIds={[]} walkingRecordId={null} errorFor={(field) => field === "walkingRecord.summary" ? "走讀摘要長度必須為 20～1500 字。" : undefined} onChange={vi.fn()} />); expect(screen.getByText("走讀摘要長度必須為 20～1500 字。")).toHaveClass("field-error"); });
test("Digital Walk options come from approved publicly listed registry", () => { renderFields(); const select = screen.getByLabelText(/關聯數位走讀/); expect(within(select).getByRole("option", { name: /DW-YG-001/ })).toBeInTheDocument(); expect(within(select).getByRole("option", { name: /DW-WT-001/ })).toBeInTheDocument(); });
test("walking cover only offers current activity references", () => { renderFields(); const options = within(screen.getByLabelText(/走讀封面圖/)).getAllByRole("option"); expect(options.map((node) => node.textContent)).toEqual(["沿用活動封面", "活動封面", "相簿圖片 1", "相簿圖片 2"]); expect(options.map((node) => (node as HTMLOptionElement).value)).toEqual(["", "cover-a", "gallery-a", "gallery-b"]); });
test("retired linked Digital Walk stays selected with warning instead of being cleared", () => { const value = { ...base, digitalWalkId: "DW-RETIRED-001" }; renderFields(value); expect(screen.getByLabelText(/關聯數位走讀/)).toHaveValue("DW-RETIRED-001"); expect(screen.getByText(/目前關聯路線已不公開；系統會保留原值/)).toBeInTheDocument(); });
test("toggle off preserves server identity and re-enable displays the same identity", () => { vi.spyOn(window, "confirm").mockReturnValue(true); const onChange = vi.fn(); const view = render(<WalkingRecordFields value={base} activityCoverAssetId={null} galleryAssetIds={[]} walkingRecordId="WR-115-003" errorFor={() => undefined} onChange={onChange} />); fireEvent.click(screen.getByRole("checkbox")); expect(onChange).toHaveBeenLastCalledWith(null); view.rerender(<WalkingRecordFields value={emptyWalkingRecord()} activityCoverAssetId={null} galleryAssetIds={[]} walkingRecordId="WR-115-003" errorFor={() => undefined} onChange={onChange} />); expect(screen.getByText("WR-115-003")).toBeInTheDocument(); });
