import { expect, test } from "vitest";
import { emptyActivityForm, matchesPublishedContent, normalizeContentForm, presentValidationIssue, validateCanonicalContent, validateWalkingMediaReference } from "./content-contracts";
import { emptyWalkingRecord } from "../components/content/WalkingRecordFields";

const activity = () => ({ ...emptyActivityForm(), id: "115-099", year: "115", name: "真實活動", dateLabel: "10/6", districts: ["中埔鄉"], venue: "場地", activityType: "走讀", topic: "地方文化", summary: "這是一段足夠長度的活動說明內容，供測試使用。" });
const walking = () => ({ ...emptyWalkingRecord(), summary: "這是一段足夠長度的走讀摘要內容，供測試使用。", routeSummary: "中埔聚落", stops: [{ name: "第一站", note: null }], fieldNotes: ["現場觀察"] });

test("legacy activity stays walkingRecord null", () => expect(normalizeContentForm("activity", activity()).walkingRecord).toBeNull());
test("walking summary is never inferred from activity summary", () => { const form = activity(); form.walkingRecord = emptyWalkingRecord(); expect(normalizeContentForm("activity", form).walkingRecord?.summary).toBe(""); });
test("valid walking form normalizes nullable fields deterministically", () => { const form = activity(); form.walkingRecord = { ...walking(), titleOverride: "  ", locationOverride: "  ", routeSummary: " 路線 ", stops: [{ name: " 站點 ", note: " " }], fieldNotes: [" 觀察 ", " "] }; expect(normalizeContentForm("activity", form).walkingRecord).toMatchObject({ titleOverride: null, locationOverride: null, routeSummary: "路線", stops: [{ name: "站點", note: null }], fieldNotes: ["觀察"] }); });
test("walking changes participate in semantic unpublished diff", () => { const base = normalizeContentForm("activity", activity()); const changed = structuredClone(base); changed.walkingRecord = walking(); expect(matchesPublishedContent(changed, base)).toBe(false); });
test("walking type-only edit is unsynced", () => { const form = activity(); form.walkingRecord = walking(); const base = normalizeContentForm("activity", form); const changed = structuredClone(base); if (changed.walkingRecord) changed.walkingRecord.type = "聚落踏查"; expect(matchesPublishedContent(changed, base)).toBe(false); });
test("walking location override edit is an unpublished semantic change", () => { const form = activity(); form.walkingRecord = walking(); const base = normalizeContentForm("activity", form); const changed = structuredClone(base); if (changed.walkingRecord) changed.walkingRecord.locationOverride = "走讀專屬地點"; expect(matchesPublishedContent(changed, base)).toBe(false); });
test("stop and field-note reorder-only edits are unsynced", () => { const form = activity(); form.walkingRecord = { ...walking(), stops: [{ name: "甲", note: null }, { name: "乙", note: null }], fieldNotes: ["一", "二"] }; const base = normalizeContentForm("activity", form); const stopsChanged = structuredClone(base); stopsChanged.walkingRecord?.stops.reverse(); const notesChanged = structuredClone(base); notesChanged.walkingRecord?.fieldNotes.reverse(); expect(matchesPublishedContent(stopsChanged, base)).toBe(false); expect(matchesPublishedContent(notesChanged, base)).toBe(false); });
test("walking technical-free identical canonical remains synced", () => { const form = activity(); form.walkingRecord = walking(); const base = normalizeContentForm("activity", form); expect(matchesPublishedContent(structuredClone(base), base)).toBe(true); });
test("foreign walking cover is blocked", () => { const form = activity(); form.coverAssetId = "cover"; form.galleryAssetIds = ["gallery"]; form.walkingRecord = { ...walking(), coverAssetId: "foreign" }; expect(validateWalkingMediaReference(normalizeContentForm("activity", form))[0]?.code).toBe("walking.cover.foreign"); });
test("activity cover and gallery references are accepted", () => { const form = activity(); form.coverAssetId = "cover"; form.galleryAssetIds = ["gallery"]; for (const id of [null, "cover", "gallery"]) { form.walkingRecord = { ...walking(), coverAssetId: id }; expect(validateWalkingMediaReference(normalizeContentForm("activity", form))).toEqual([]); } });
test("unknown or unpublished Digital Walk ID is blocked", () => { const form = activity(); form.walkingRecord = { ...walking(), digitalWalkId: "DW-NOT-PUBLIC" }; expect(validateWalkingMediaReference(normalizeContentForm("activity", form))[0]?.code).toBe("walking.digitalWalkId.unknown"); });
test.each([[19,false],[20,true],[1500,true],[1501,false]] as const)("walking summary boundary %i valid=%s", (length, valid) => { const form = activity(); form.walkingRecord = { ...walking(), summary: "字".repeat(length) }; const result = validateCanonicalContent("activity", normalizeContentForm("activity", form)); expect(!result.errors.some((issue) => issue.code === "walking.summary.length")).toBe(valid); });
test("removed selected gallery asset becomes an explicit foreign-cover error", () => { const form = activity(); form.galleryAssetIds = []; form.walkingRecord = { ...walking(), coverAssetId: "removed-gallery-asset" }; expect(validateWalkingMediaReference(normalizeContentForm("activity", form))).toContainEqual(expect.objectContaining({ code: "walking.cover.foreign" })); });
test("walking disable is an unpublished semantic change", () => { const form = activity(); form.walkingRecord = walking(); const published = normalizeContentForm("activity", form); const disabled = structuredClone(published); disabled.walkingRecord = null; expect(matchesPublishedContent(disabled, published)).toBe(false); });
test("invalid walking type is rejected by canonical validator", () => { const form = activity(); form.walkingRecord = { ...walking(), type: "未知" as never }; expect(validateCanonicalContent("activity", normalizeContentForm("activity", form)).errors.some((issue) => issue.code === "walking.type")).toBe(true); });
test("blank stop name is rejected when row survives normalization", () => { const form = activity(); form.walkingRecord = { ...walking(), stops: [{ name: "", note: "有說明" }] }; expect(validateCanonicalContent("activity", normalizeContentForm("activity", form)).errors.some((issue) => issue.code === "walking.stop.name")).toBe(true); });
test("walking errors map to focused Chinese UI labels", () => expect(presentValidationIssue({ field: "walkingRecord.stops[1].name", code: "walking.stop.name", message: "站點名稱必填。" })).toMatchObject({ field: "站點 2名稱", targetId: "walking-stop-1-name" }));
