import test from "node:test";
import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { createClient } from "../../admin/node_modules/@supabase/supabase-js/dist/index.mjs";

const enabled=process.env.YIMI_RUN_CLOUD_PUBLICATION_SNAPSHOT_INTEGRATION==="1";
const origin="https://yimi-story-admin.pages.dev";
const makeClient=(url,key)=>createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},global:{headers:{Origin:origin}}});
const png=()=>{const b=new Uint8Array(24);b.set([137,80,78,71,13,10,26,10],0);b.set([73,72,68,82],12);new DataView(b.buffer).setUint32(16,640);new DataView(b.buffer).setUint32(20,480);return b;};
async function exact(service,table,configure=(q)=>q){const{count,error}=await configure(service.from(table).select("id",{count:"exact",head:true}));if(error)throw error;return count??0;}
async function baseline(service){const{data,error}=await service.from("media_assets").select("id,content_id,source,role,sort_order,legacy_path,original_filename,mime_type,byte_size,width,height,sha256,alt_text,rights_status,contains_portrait,legacy_asset_key,published_snapshot_id").eq("source","github_legacy").order("id");if(error)throw error;const bucket=async(name)=>{const{data:objects,error:e}=await service.storage.from(name).list("",{limit:1000});if(e)throw e;return objects.length;};return{items:await exact(service,"content_items"),classes:await exact(service,"content_items",q=>q.eq("content_type","class_result")),activities:await exact(service,"content_items",q=>q.eq("content_type","activity")),snapshots:await exact(service,"publication_snapshots"),drafts:await exact(service,"content_drafts"),media:await exact(service,"media_assets"),legacy:await exact(service,"media_assets",q=>q.eq("source","github_legacy")),cmsDraft:await exact(service,"media_assets",q=>q.eq("source","cms_draft")),publications:await exact(service,"github_publications"),draftObjects:await bucket("cms-drafts"),publicObjects:await bucket("cms-public"),digest:createHash("sha256").update(JSON.stringify(data)).digest("hex")};}
const validation={valid:true,errors:[],warnings:[]};
const classData=(id,cover=null)=>({id,year:Number(id.slice(3,6)),title:"Stage 7A 發布快照測試班級",className:"地方知識測試班",instructor:"測試講師",description:"這是一段符合最小長度的班級成果內容，只用於驗證不可變發布快照流程。",districts:["朴子市"],venue:"測試教室",tags:["地方知識"],sdgs:["SDG 4"],displayOrder:1,internalNotes:"SECRET-INTERNAL-PUBLICATION-TEST",publicNotes:"公開測試備註",coverAssetId:cover,galleryAssetIds:[]});
const activityData=(id,cover)=>({id,year:Number(id.slice(0,3)),name:"Stage 7A 發布快照測試活動",startDate:"2027-08-28",endDate:null,dateLabel:"8/28",districts:["朴子市"],venue:"測試場地",projectName:null,activityType:"講座",topic:"地方文化",sdgs:["SDG 4"],summary:"這是一段符合最小長度的活動效益摘要，只用於驗證不可變發布快照流程。",participants:20,partnerOrganizations:null,leader:null,keywords:[],videoUrl:null,relatedUrl:null,featured:false,internalNotes:"SECRET-INTERNAL-PUBLICATION-TEST",publicNotes:null,coverAssetId:cover,galleryAssetIds:[]});

test("Stage 7A Cloud temporary class/activity/existing-style snapshot與精確清理",{skip:!enabled,timeout:180_000},async()=>{
  const url=process.env.YIMI_CLOUD_SUPABASE_URL,key=process.env.YIMI_CLOUD_PUBLISHABLE_KEY,serviceKey=process.env.YIMI_CLOUD_SERVICE_ROLE_KEY;assert.ok(url&&key&&serviceKey,"Cloud publication env missing");
  const service=makeClient(url,serviceKey),before=await baseline(service);assert.deepEqual({...before,digest:undefined},{items:119,classes:56,activities:63,snapshots:119,drafts:0,media:714,legacy:714,cmsDraft:0,publications:0,draftObjects:0,publicObjects:0,digest:undefined});assert.equal(before.digest,"395f49c6767d46b6b4a485dc6655cc673c4603938a70c78a6ac342d2554d08af");
  const suffix=randomUUID().replace(/\D/g,"").padEnd(3,"7").slice(0,3),password=`Safe-${randomUUID()}!`,email=`cloud-publication-${randomUUID().slice(0,8)}@example.test`;let userId="";const contentIds=[],draftIds=[],mediaIds=[],objects=[];
  try{
    const created=await service.auth.admin.createUser({email,password,email_confirm:true});if(created.error)throw created.error;userId=created.data.user.id;assert.equal((await service.from("admin_users").insert({user_id:userId,email,is_active:true})).error,null);const active=makeClient(url,key);assert.equal((await active.auth.signInWithPassword({email,password})).error,null);
    const create=async(type,id,dataFactory,withCover=true)=>{const item=await service.from("content_items").insert({content_type:type,public_id:id,created_by:userId}).select("id,published_snapshot_id").single();if(item.error)throw item.error;contentIds.push(item.data.id);const draft=await service.from("content_drafts").insert({content_id:item.data.id,data:dataFactory(id,null),validation_result:validation,status:"draft",created_by:userId,updated_by:userId}).select("id,revision").single();if(draft.error)throw draft.error;draftIds.push(draft.data.id);let cover=null;if(withCover){const mediaId=randomUUID(),path=`${userId}/${item.data.id}/${mediaId}/${mediaId}.png`;objects.push(path);mediaIds.push(mediaId);assert.equal((await active.storage.from("cms-drafts").upload(path,png(),{contentType:"image/png"})).error,null);const verified=await active.functions.invoke("validate-media-upload",{body:{contentId:item.data.id,draftId:draft.data.id,mediaId,bucket:"cms-drafts",objectPath:path,role:"cover",originalFilename:"stage7a.png",declaredMimeType:"image/png"}});assert.equal(verified.error,null);cover=mediaId;}
      const saved=await active.rpc("save_content_draft_with_media",{p_draft_id:draft.data.id,p_data:dataFactory(id,cover),p_validation_result:validation,p_status:"validated",p_media_metadata:cover?[{id:cover,altText:"Stage 7A 測試封面",containsPortrait:"no",rightsStatus:"owned"}]:[]});assert.equal(saved.error,null);return{item:item.data,draftId:draft.data.id,revision:saved.data.revision,cover};};
    const klass=await create("class_result",`CR-116-${suffix}`,classData);const activity=await create("activity",`116-${suffix}`,activityData);
    for(const current of [klass,activity]){const checked=await active.functions.invoke("prepare-publication-snapshot",{body:{action:"validate",draftId:current.draftId,expectedRevision:current.revision}});assert.equal(checked.error,null);assert.equal(checked.data.preparation.valid,true,JSON.stringify(checked.data.preparation.errors.map(({field,code})=>({field,code}))));assert.equal(JSON.stringify(checked.data.preparation).includes("SECRET-INTERNAL-PUBLICATION-TEST"),false);assert.equal("mediaManifest" in checked.data.preparation,false);const first=await active.functions.invoke("prepare-publication-snapshot",{body:{action:"create",draftId:current.draftId,expectedRevision:current.revision}});assert.equal(first.error,null);const second=await active.functions.invoke("prepare-publication-snapshot",{body:{action:"create",draftId:current.draftId,expectedRevision:current.revision}});assert.equal(second.error,null);assert.equal(second.data.snapshot.checksum_sha256,first.data.snapshot.checksum_sha256);assert.equal((await exact(service,"publication_snapshots",q=>q.eq("source_draft_id",current.draftId).eq("source_revision",current.revision))),1);assert.equal((await service.from("content_items").select("published_snapshot_id").eq("id",current.item.id).single()).data.published_snapshot_id,null);}
    const existing=await create("class_result",`CR-117-${suffix}`,classData,false);const baselineSnapshot=await service.from("publication_snapshots").insert({content_id:existing.item.id,source_revision:0,schema_version:"1.0",snapshot_data:classData(`CR-117-${suffix}`,null),media_manifest:[],checksum_sha256:"b".repeat(64),status:"baseline_published",created_by:userId,snapshot_source:"baseline_import"}).select("id").single();if(baselineSnapshot.error)throw baselineSnapshot.error;assert.equal((await service.from("content_items").update({published_snapshot_id:baselineSnapshot.data.id}).eq("id",existing.item.id)).error,null);const prepared=await active.functions.invoke("prepare-publication-snapshot",{body:{action:"create",draftId:existing.draftId,expectedRevision:existing.revision}});assert.equal(prepared.error,null);assert.equal((await service.from("content_items").select("published_snapshot_id").eq("id",existing.item.id).single()).data.published_snapshot_id,baselineSnapshot.data.id);
    const changed=await active.rpc("save_content_draft_with_media",{p_draft_id:klass.draftId,p_data:{...classData(`CR-116-${suffix}`,klass.cover),title:"revision changed"},p_validation_result:{valid:false,errors:[],warnings:[]},p_status:"draft",p_media_metadata:[]});assert.equal(changed.error,null);const race=await active.functions.invoke("prepare-publication-snapshot",{body:{action:"create",draftId:klass.draftId,expectedRevision:klass.revision}});assert.ok(race.error);assert.equal(await exact(service,"github_publications"),0);assert.equal(await exact(service,"media_assets",q=>q.eq("source","cms_public")),0);
  }finally{
    if(contentIds.length)await service.from("content_items").update({published_snapshot_id:null}).in("id",contentIds);if(contentIds.length)await service.from("publication_snapshots").delete().in("content_id",contentIds);if(objects.length)await service.storage.from("cms-drafts").remove(objects);if(mediaIds.length)await service.from("media_assets").delete().in("id",mediaIds);if(draftIds.length)await service.from("content_drafts").delete().in("id",draftIds);if(contentIds.length)await service.from("content_items").delete().in("id",contentIds);if(userId){await service.from("admin_users").delete().eq("user_id",userId);await service.auth.admin.deleteUser(userId);}
  }
  assert.deepEqual(await baseline(service),before);
});
