import test from "node:test";
import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { createClient } from "../../admin/node_modules/@supabase/supabase-js/dist/index.mjs";

const preflightOnly=process.env.YIMI_RUN_CLOUD_IMAGE_EDIT_PREFLIGHT==="1";
const enabled=process.env.YIMI_RUN_CLOUD_IMAGE_EDIT_INTEGRATION==="1"||preflightOnly;
const preserveExistingAcceptanceData=process.env.YIMI_CLOUD_IMAGE_EDIT_PRESERVE_EXISTING==="1";
const makeClient=(url,key)=>createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},global:{headers:{Origin:"https://yimi-story-admin.pages.dev"}}});
const png=(width=640,height=480)=>{const b=new Uint8Array(24);b.set([137,80,78,71,13,10,26,10],0);b.set([73,72,68,82],12);new DataView(b.buffer).setUint32(16,width);new DataView(b.buffer).setUint32(20,height);return b;};
const exact=async(client,table,configure=(q)=>q)=>{const{count,error}=await configure(client.from(table).select("id",{count:"exact",head:true}));if(error)throw error;return count??0;};
async function baseline(service){const{data,error}=await service.from("media_assets").select("id,content_id,source,role,sort_order,legacy_path,original_filename,mime_type,byte_size,width,height,sha256,alt_text,rights_status,contains_portrait,legacy_asset_key,published_snapshot_id").eq("source","github_legacy").order("id");if(error)throw error;const bucket=async(name)=>{const{data:objects,error:e}=await service.storage.from(name).list("",{limit:1000});if(e)throw e;return objects.length;};return{items:await exact(service,"content_items"),snapshots:await exact(service,"publication_snapshots"),drafts:await exact(service,"content_drafts"),media:await exact(service,"media_assets"),legacy:await exact(service,"media_assets",q=>q.eq("source","github_legacy")),cmsDraft:await exact(service,"media_assets",q=>q.eq("source","cms_draft")),publications:await exact(service,"github_publications"),draftObjects:await bucket("cms-drafts"),publicObjects:await bucket("cms-public"),digest:createHash("sha256").update(JSON.stringify(data)).digest("hex")};}

test("Stage 6.5 production temporary class/activity image versions are fully cleaned",{skip:!enabled,timeout:120_000},async()=>{
  const url=process.env.YIMI_CLOUD_SUPABASE_URL,key=process.env.YIMI_CLOUD_PUBLISHABLE_KEY,serviceKey=process.env.YIMI_CLOUD_SERVICE_ROLE_KEY;assert.ok(url&&key&&serviceKey,"cloud image edit env required");const service=makeClient(url,serviceKey),before=await baseline(service);
  const clean={items:119,snapshots:119,drafts:0,media:714,legacy:714,cmsDraft:0,publications:0,draftObjects:0,publicObjects:0,digest:"395f49c6767d46b6b4a485dc6655cc673c4603938a70c78a6ac342d2554d08af"};
  if(preserveExistingAcceptanceData){assert.deepEqual({...before,draftObjects:0},{...clean,items:120,drafts:2,media:717,cmsDraft:3},"only the inventoried Stage 6.5 acceptance data may coexist with this fixture");assert.ok(before.draftObjects>0,"acceptance Storage objects must still exist");}else assert.deepEqual(before,clean);if(preflightOnly)return;
  const suffix=randomUUID().slice(0,8),password=`Safe-${randomUUID()}!`,users=[],contentIds=[],objects=[];
  const createIdentity=async(kind,isAdmin=null)=>{const email=`image-edit-${kind}-${suffix}@example.test`;const{data,error}=await service.auth.admin.createUser({email,password,email_confirm:true});if(error)throw error;users.push(data.user.id);if(isAdmin!==null){const{error:e}=await service.from("admin_users").insert({user_id:data.user.id,email,is_active:isAdmin});if(e)throw e;}const signed=makeClient(url,key);const{error:s}=await signed.auth.signInWithPassword({email,password});if(s)throw s;return{client:signed,id:data.user.id};};
  const active=await createIdentity("active",true),inactive=await createIdentity("inactive",false),nonAdmin=await createIdentity("user");
  const upload=async({contentId,draftId,role,width,originalMediaId=null,transformation=null,name})=>{const mediaId=randomUUID(),path=`${active.id}/${contentId}/${mediaId}/${mediaId}.png`;objects.push(path);assert.equal((await active.client.storage.from("cms-drafts").upload(path,png(width,width===480?640:480),{contentType:"image/png"})).error,null);const{data,error}=await active.client.functions.invoke("validate-media-upload",{body:{contentId,draftId,mediaId,bucket:"cms-drafts",objectPath:path,role,originalFilename:name,declaredMimeType:"image/png",...(originalMediaId?{originalMediaId,transformation}:{})}});assert.equal(error,null);assert.ok(data.media);return data.media;};
  const createContent=async(type)=>{const publicId=`TEST-IMAGE-EDIT-${type==="class_result"?"CLASS":"ACTIVITY"}-${suffix}`;const{data:item,error}=await service.from("content_items").insert({content_type:type,public_id:publicId,created_by:active.id}).select("id").single();if(error)throw error;contentIds.push(item.id);const{data:draft,error:de}=await service.from("content_drafts").insert({content_id:item.id,data:{coverAssetId:null,galleryAssetIds:[]},validation_result:{valid:true,errors:[],warnings:[]},status:"validated",created_by:active.id,updated_by:active.id}).select("id,revision").single();if(de)throw de;return{contentId:item.id,draftId:draft.id,revision:draft.revision,publicId};};
  try{
    const klass=await createContent("class_result"),activity=await createContent("activity");
    const classRoot=await upload({...klass,role:"cover",width:640,name:"class-cover.png"});const activityRoot=await upload({...activity,role:"gallery",width:641,name:"activity-portrait.png"});const activitySecond=await upload({...activity,role:"gallery",width:642,name:"activity-second.png"});
    const mediaBeforeAttach=await exact(service,"media_assets"),objectsBeforeAttach=objects.length;
    const attachedRoot=await active.client.rpc("attach_existing_draft_media",{p_draft_id:klass.draftId,p_media_id:classRoot.id});assert.equal(attachedRoot.error,null);assert.equal(attachedRoot.data.data.coverAssetId,classRoot.id);
    const reloadedRoot=await active.client.from("content_drafts").select("data,revision").eq("id",klass.draftId).single();assert.equal(reloadedRoot.error,null);assert.equal(reloadedRoot.data.data.coverAssetId,classRoot.id);assert.equal((await active.client.rpc("attach_existing_draft_media",{p_draft_id:klass.draftId,p_media_id:classRoot.id})).error.code,"23505");
    assert.equal((await active.client.rpc("attach_existing_draft_media",{p_draft_id:activity.draftId,p_media_id:classRoot.id})).error.code,"42501");
    assert.equal((await active.client.rpc("attach_existing_draft_media",{p_draft_id:activity.draftId,p_media_id:activityRoot.id})).error,null);assert.equal((await active.client.rpc("attach_existing_draft_media",{p_draft_id:activity.draftId,p_media_id:activitySecond.id})).error,null);
    assert.equal(await exact(service,"media_assets"),mediaBeforeAttach);assert.equal(objects.length,objectsBeforeAttach);
    const save=async(record,data,ids)=>{const{data:saved,error}=await active.client.rpc("save_content_draft_with_media",{p_draft_id:record.draftId,p_data:data,p_validation_result:{valid:true,errors:[],warnings:[]},p_status:"validated",p_media_metadata:ids.map((id,index)=>({id,altText:index?"第二張":"保留的替代文字",containsPortrait:index?"no":"yes",rightsStatus:index?"owned":"authorized"}))});assert.equal(error,null);return saved;};
    await save(klass,{coverAssetId:classRoot.id,galleryAssetIds:[]},[classRoot.id]);await save(activity,{coverAssetId:null,galleryAssetIds:[activityRoot.id,activitySecond.id]},[activityRoot.id,activitySecond.id]);
    const classTransform={rotation:90,crop:{x:0,y:0,width:1,height:1,aspectRatio:"original"},normalizedOrientation:true,originalOrientation:6};const activityTransform={rotation:0,crop:{x:.1,y:.1,width:.8,height:.8,aspectRatio:"1:1"},normalizedOrientation:true,originalOrientation:6};
    const failedDerived=await upload({...klass,role:"cover",width:479,name:"class-cover.png",originalMediaId:classRoot.id,transformation:classTransform});const failedAttach=await active.client.rpc("attach_derived_draft_media",{p_draft_id:klass.draftId,p_current_media_id:activityRoot.id,p_derived_media_id:failedDerived.id});assert.ok(failedAttach.error);const afterFailedAttach=await active.client.from("content_drafts").select("data").eq("id",klass.draftId).single();assert.equal(afterFailedAttach.data.data.coverAssetId,classRoot.id);assert.equal((await active.client.rpc("delete_unreferenced_draft_media",{p_media_id:failedDerived.id})).data,true);assert.equal((await active.client.storage.from("cms-drafts").remove([failedDerived.object_path])).error,null);objects.splice(objects.indexOf(failedDerived.object_path),1);
    const classEdited=await upload({...klass,role:"cover",width:480,name:"class-cover.png",originalMediaId:classRoot.id,transformation:classTransform});const activityEdited=await upload({...activity,role:"gallery",width:480,name:"activity-portrait.png",originalMediaId:activityRoot.id,transformation:activityTransform});
    const attachedClass=await active.client.rpc("attach_derived_draft_media",{p_draft_id:klass.draftId,p_current_media_id:classRoot.id,p_derived_media_id:classEdited.id});assert.equal(attachedClass.error,null);assert.equal(attachedClass.data.data.coverAssetId,classEdited.id);assert.equal(attachedClass.data.status,"draft");
    const attachedActivity=await active.client.rpc("attach_derived_draft_media",{p_draft_id:activity.draftId,p_current_media_id:activityRoot.id,p_derived_media_id:activityEdited.id});assert.equal(attachedActivity.error,null);assert.deepEqual(attachedActivity.data.data.galleryAssetIds,[activityEdited.id,activitySecond.id]);
    const edited=await service.from("media_assets").select("id,original_media_id,transformation,alt_text,contains_portrait,rights_status,width,height,sha256,object_path").in("id",[classEdited.id,activityEdited.id]);assert.equal(edited.error,null);assert.equal(edited.data.length,2);assert.ok(edited.data.every(row=>row.original_media_id&&row.transformation.normalizedOrientation&&row.alt_text==="保留的替代文字"&&row.contains_portrait===true&&row.rights_status==="authorized"));assert.notEqual(edited.data.find(row=>row.id===classEdited.id).sha256,classRoot.sha256);
    for(const row of edited.data)assert.equal((await active.client.storage.from("cms-drafts").createSignedUrl(row.object_path,900)).error,null);
    for(const blocked of [makeClient(url,key),inactive.client,nonAdmin.client])assert.ok((await blocked.rpc("restore_original_draft_media",{p_draft_id:klass.draftId,p_current_media_id:classEdited.id})).error);
    const restoreClass=await active.client.rpc("restore_original_draft_media",{p_draft_id:klass.draftId,p_current_media_id:classEdited.id});assert.equal(restoreClass.error,null);assert.equal(restoreClass.data.data.coverAssetId,classRoot.id);const restoreActivity=await active.client.rpc("restore_original_draft_media",{p_draft_id:activity.draftId,p_current_media_id:activityEdited.id});assert.equal(restoreActivity.error,null);assert.deepEqual(restoreActivity.data.data.galleryAssetIds,[activityRoot.id,activitySecond.id]);
    for(const row of edited.data){assert.equal((await active.client.rpc("delete_unreferenced_draft_media",{p_media_id:row.id})).data,true);assert.equal((await active.client.storage.from("cms-drafts").remove([row.object_path])).error,null);objects.splice(objects.indexOf(row.object_path),1);}
    assert.equal((await service.from("media_assets").select("id",{count:"exact",head:true}).in("id",[classRoot.id,activityRoot.id,activitySecond.id])).count,3);
  }finally{
    if(contentIds.length)await service.from("content_items").delete().in("id",contentIds);if(objects.length)await service.storage.from("cms-drafts").remove(objects);if(users.length){await service.from("admin_users").delete().in("user_id",users);for(const id of users)await service.auth.admin.deleteUser(id);}
  }
  assert.deepEqual(await baseline(service),before);
});
