import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const migration=await readFile(new URL("../../supabase/migrations/202608270001_media_edit_versions.sql",import.meta.url),"utf8");
const reattachMigration=await readFile(new URL("../../supabase/migrations/202608280001_attach_existing_draft_media.sql",import.meta.url),"utf8");
const edge=await readFile(new URL("../../supabase/functions/validate-media-upload/index.ts",import.meta.url),"utf8");
const handler=await readFile(new URL("../../supabase/functions/validate-media-upload/handler.ts",import.meta.url),"utf8");

test("Stage 6.5 migration只add nullable version欄位與安全FK",()=>{assert.match(migration,/add column original_media_id uuid[\s\S]*add column transformation jsonb/i);assert.match(migration,/foreign key \(original_media_id\)[\s\S]*on delete restrict/i);assert.doesNotMatch(migration,/alter column (original_media_id|transformation) set not null/i);});
test("derived仍是cms_draft且必須orientation normalized與crop object",()=>{assert.match(migration,/source = 'cms_draft'[\s\S]*normalizedOrientation[\s\S]*rotation[\s\S]*crop/i);assert.doesNotMatch(migration,/cms_edited/i);});
test("migration不回填Legacy、不重寫snapshot且不刪資料",()=>{const schemaChanges=migration.slice(0,migration.indexOf("create function public.attach_derived_draft_media"));assert.doesNotMatch(schemaChanges,/(update|delete from|insert into) public\.(media_assets|publication_snapshots|content_items|github_publications)/i);assert.doesNotMatch(migration,/(update|delete from|insert into) public\.(publication_snapshots|content_items|github_publications)/i);});
test("attach RPC只允許active owner、同content draft與root original",()=>{assert.match(migration,/function public\.attach_derived_draft_media[\s\S]*is_active_admin[\s\S]*created_by = auth\.uid\(\)[\s\S]*original_media_id is null/i);});
test("attach與restore保持Gallery ordinality並降回draft",()=>{for(const name of["attach_derived_draft_media","restore_original_draft_media"]){const start=migration.indexOf(`function public.${name}`);const block=migration.slice(start,start+7000);assert.match(block,/with ordinality/i);assert.match(block,/status = 'draft'/i);assert.match(block,/updated_by = auth\.uid\(\)/i);}});
test("orphan刪除同時阻擋canonical reference與derived child",()=>{const start=migration.indexOf("function public.delete_unreferenced_draft_media");const block=migration.slice(start);assert.match(block,/coverAssetId[\s\S]*galleryAssetIds/i);assert.match(block,/child\.original_media_id = p_media_id/i);});
test("browser不可直接寫media或cms-public",()=>{assert.doesNotMatch(migration,/grant (insert|update|delete)[^;]*media_assets[^;]*authenticated/i);assert.doesNotMatch(migration,/cms-public|cms_public/i);});
test("RPC不授權anon且只授權authenticated/service_role",()=>{assert.match(migration,/revoke all on function public\.attach_derived_draft_media[^;]*from public, anon/i);assert.match(migration,/grant execute on function public\.restore_original_draft_media[^;]*to authenticated, service_role/i);});
test("既有未引用original media可原子reattach且拒絕derived與跨content",()=>{assert.match(reattachMigration,/create function public\.attach_existing_draft_media\s*\(/i);assert.match(reattachMigration,/content_id = v_draft\.content_id/i);assert.match(reattachMigration,/draft_id = v_draft\.id/i);assert.match(reattachMigration,/source = 'cms_draft'/i);assert.match(reattachMigration,/original_media_id is null/i);assert.match(reattachMigration,/transformation is null/i);assert.match(reattachMigration,/upload_status = 'ready'/i);assert.match(reattachMigration,/created_by = auth\.uid\(\)/i);assert.match(reattachMigration,/jsonb_array_length\(v_gallery\) >= 20/i);assert.match(reattachMigration,/revoke all on function public\.attach_existing_draft_media\(uuid, uuid\) from public, anon/i);assert.match(reattachMigration,/grant execute on function public\.attach_existing_draft_media\(uuid, uuid\) to authenticated, service_role/i);assert.doesNotMatch(reattachMigration,/delete\s+from|drop\s+table|truncate/i);});
test("validate-media-upload仍複驗blob並限制derived root來源",()=>{assert.match(handler,/detect\(bytes\)[\s\S]*dimensions\(bytes,mime\)[\s\S]*checksum\(bytes\)/i);assert.match(edge,/source","cms_draft"[\s\S]*original_media_id[\s\S]*data\.role!==input\.role/i);assert.doesNotMatch(edge,/source","github_legacy"/i);});
