import test from "node:test";
import assert from "node:assert/strict";
import { createValidateMediaUploadHandler } from "../../supabase/functions/validate-media-upload/handler.ts";

const origin="https://yimi-story-admin.pages.dev";const user="11111111-1111-4111-8111-111111111111",content="22222222-2222-4222-8222-222222222222",draft="33333333-3333-4333-8333-333333333333",media="44444444-4444-4444-8444-444444444444";
const path=`${user}/${content}/${media}/${media}.png`;
const png=()=>{const b=new Uint8Array(24);b.set([137,80,78,71,13,10,26,10],0);b.set([73,72,68,82],12);new DataView(b.buffer).setUint32(16,640);new DataView(b.buffer).setUint32(20,480);return b;};
const body=(objectPath=path)=>({contentId:content,draftId:draft,mediaId:media,bucket:"cms-drafts",objectPath,role:"cover",originalFilename:"test.png",declaredMimeType:"image/png"});
const request=(value=body(),requestOrigin=origin)=>new Request("https://example/functions/v1/validate-media-upload",{method:"POST",headers:{origin:requestOrigin,authorization:"Bearer safe-test",'content-type':'application/json'},body:JSON.stringify(value)});
function deps(bytes=png(),status="active"){let removed=0,created=0;return{state:()=>({removed,created}),value:{verify:async()=>({status,userId:user}),download:async()=>bytes,create:async(input,verified)=>{created++;return{id:input.mediaId,source:"cms_draft",width:verified.width,height:verified.height,sha256:verified.sha256};},remove:async()=>{removed++;}}};}

test("active admin對own prefix的PNG完成server header、尺寸、checksum與row建立",async()=>{const d=deps();const response=await createValidateMediaUploadHandler(origin,d.value)(request());const result=await response.json();assert.equal(response.status,200);assert.equal(result.media.source,"cms_draft");assert.equal(result.media.width,640);assert.match(result.media.sha256,/^[0-9a-f]{64}$/);assert.deepEqual(d.state(),{removed:0,created:1});});
test("fake JPG/corrupt image拒絕並清除object",async()=>{const d=deps(new TextEncoder().encode("not jpeg"));const input={...body(),objectPath:path.replace(/\.png$/,'.jpg'),declaredMimeType:"image/jpeg"};const response=await createValidateMediaUploadHandler(origin,d.value)(request(input));assert.equal(response.status,400);assert.deepEqual(d.state(),{removed:1,created:0});});
test("DB row建立失敗時補償清除已上傳object",async()=>{let removed=0;const d=deps();d.value.create=async()=>{throw new Error("media_record_failed")};d.value.remove=async()=>{removed++};const response=await createValidateMediaUploadHandler(origin,d.value)(request());assert.equal(response.status,400);assert.equal(removed,1);});
test("other prefix、unknown origin與inactive admin均阻擋",async()=>{const d=deps();assert.equal((await createValidateMediaUploadHandler(origin,d.value)(request({...body(),objectPath:`99999999-9999-4999-8999-999999999999/${content}/${media}/${media}.png`}))).status,403);assert.equal((await createValidateMediaUploadHandler(origin,d.value)(request(body(),"https://attacker.example"))).status,403);const inactive=deps(png(),"inactive");assert.equal((await createValidateMediaUploadHandler(origin,inactive.value)(request())).status,403);});
test("CORS preflight精確允許production origin且無wildcard",async()=>{const d=deps();const response=await createValidateMediaUploadHandler(origin,d.value)(new Request("https://example",{method:"OPTIONS",headers:{origin}}));assert.equal(response.status,204);assert.equal(response.headers.get("access-control-allow-origin"),origin);assert.notEqual(response.headers.get("access-control-allow-origin"),"*");});
