import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const migration=await readFile(new URL("../../supabase/migrations/202609020001_publication_media_promotion.sql",import.meta.url),"utf8");
const edge=await readFile(new URL("../../supabase/functions/prepare-publication-media/index.ts",import.meta.url),"utf8");
const handler=await readFile(new URL("../../supabase/functions/prepare-publication-media/handler.ts",import.meta.url),"utf8");

test("Stage 7B additive schema不回填baseline或改published pointer",()=>{assert.match(migration,/create table public\.publication_media_preparations/i);assert.match(migration,/create table public\.publication_media_mappings/i);const beforeFunctions=migration.slice(0,migration.indexOf("create function public.begin_publication_media_preparation"));assert.doesNotMatch(beforeFunctions,/(update|delete from|insert into) public\.(content_items|publication_snapshots|content_drafts|github_publications)/i);assert.doesNotMatch(migration,/update public\.(content_items|publication_snapshots|content_drafts|github_publications)/i);});
test("mapping保存snapshot/source/public identity、role/order與frozen metadata",()=>{for(const value of ["publication_snapshot_id","source_media_id","public_media_id","source_checksum_sha256","public_checksum_sha256","role","position","public_path","frozen_metadata"])assert.match(migration,new RegExp(value));assert.match(migration,/unique \(publication_snapshot_id, role, position\)/i);});
test("只允許1.1 draft ready snapshot進入promotion",()=>{for(const fn of ["begin_publication_media_preparation","register_publication_media_asset","finalize_publication_media_preparation"]){const start=migration.indexOf(`create function public.${fn}`);assert.ok(start>=0);assert.match(migration.slice(start,start+7000),/schema_version <> '1\.1'/i);}assert.match(edge,/snapshot\.schema_version !== "1\.1"/);assert.match(edge,/snapshot\.snapshot_source !== "draft"/);});
test("Edge不讀current publication metadata且完全使用snapshot manifest",()=>{const select=edge.match(/\.from\("media_assets"\)[\s\S]*?\.select\("([^"]+)"\)/)?.[1]??"";for(const forbidden of ["alt_text","caption","credit","rights_status","contains_portrait","portrait_consent","mime_type","byte_size","width","height"])assert.equal(select.includes(forbidden),false,forbidden);assert.match(edge,/const manifest = snapshot\.media_manifest/);assert.match(migration,/frozen_metadata is distinct from v_entry/i);});
test("deterministic path、never overwrite與checksum/dimension驗證存在",()=>{assert.match(edge,/content\/\$\{contentId\}\/\$\{entry\.mediaId\}\/\$\{entry\.sha256\}\.\$\{entry\.extension\}/);assert.match(edge,/upsert: false/);assert.match(edge,/SOURCE_CHECKSUM_MISMATCH/);assert.match(edge,/DESTINATION_CONFLICT/);assert.match(edge,/size\?\.width !== entry\.width/);assert.match(edge,/bytes\.length !== entry\.byteSize/);});
test("Legacy只建立logical mapping且cms_draft原圖不刪除",()=>{const finalize=migration.slice(migration.indexOf("create function public.finalize_publication_media_preparation"));assert.match(finalize,/source' = 'github_legacy'/i);assert.match(finalize,/'github_legacy'.*v_entry ->> 'legacyPath'/is);assert.doesNotMatch(edge,/storage\.from\("cms-drafts"\)\.remove/);assert.doesNotMatch(migration,/delete from public\.media_assets/i);});
test("browser無mapping/public media寫入權且Edge不含GitHub或發布pointer",()=>{assert.match(migration,/revoke insert, update, delete on table public\.publication_media_preparations from authenticated/i);assert.match(migration,/revoke insert, update, delete on table public\.publication_media_mappings from authenticated/i);assert.match(migration,/revoke all on function public\.register_publication_media_asset[\s\S]*from public, anon, authenticated/i);assert.doesNotMatch(edge,/github_publications|update[\s\S]{0,80}published_snapshot_id|published_snapshot_id[\s\S]{0,80}update/i);assert.doesNotMatch(handler,/service.role|service_role|SUPABASE_SERVICE_ROLE_KEY/i);});
