import test from "node:test";
import assert from "node:assert/strict";
import settings from "../../config/content-settings.json" with { type: "json" };
import { buildPublicationExportDryRun, findInternalOnlyFieldPaths, publicationSnapshotChecksum, validatePublicationPreparation } from "../../tools/publication/final-validation.mjs";

function klass() { return { id:"CR-116-001",year:116,title:"地方木作班花絮與成果",className:"地方木作班",instructor:"測試老師",description:"這是一段符合最小長度的班級課程介紹，用來驗證發布前資料契約。",districts:["朴子市"],venue:"測試教室",tags:["木作"],sdgs:["SDG 4"],displayOrder:1,internalNotes:"SECRET-STAGE7A",publicNotes:null,coverAssetId:"cover-key",galleryAssetIds:["gallery-key"] }; }
function media(overrides={}) { return { id:"11111111-1111-4111-8111-111111111111",legacyAssetKey:"cover-key",source:"github_legacy",role:"cover",sortOrder:0,legacyPath:"public/images/example/cover.jpg",sha256:"a".repeat(64),uploadStatus:"ready",altText:"",deletedAt:null,...overrides }; }
const run=(overrides={})=>validatePublicationPreparation({contentType:"class_result",data:klass(),revision:3,draftStatus:"validated",draftValidation:{valid:true,errors:[],warnings:[]},media:[media(),media({id:"22222222-2222-4222-8222-222222222222",legacyAssetKey:"gallery-key",role:"gallery",legacyPath:"public/images/example/01.jpg"})],settings,legacy:true,...overrides});

test("最終檢查產生穩定公開投影、ordered manifest且不洩漏internalNotes",async()=>{const first=await run(),second=await run();assert.equal(first.valid,true);assert.equal(first.checksum,second.checksum);assert.deepEqual(first.mediaManifest.map(x=>[x.role,x.sortOrder]),[["cover",0],["gallery",1]]);assert.equal(JSON.stringify(first.publicData).includes("internalNotes"),false);assert.equal(first.exportDryRun.includes("SECRET-STAGE7A"),false);});
test("公開欄位與internalNotes值相同不構成洩漏",async()=>{const same="TEST";const result=await run({data:{...klass(),publicNotes:same,internalNotes:same}});assert.equal(result.valid,true);assert.equal(result.errors.some(x=>x.code==="internal_notes_leak"||x.code==="internal_notes_export_leak"),false);assert.equal(result.publicData.publicNotes,same);});
test("summary、name與keywords合法重複internalNotes文字",()=>{for(const publicData of [{summary:"社區走讀"},{name:"成果展"},{keywords:["社區走讀","成果展"]}]){assert.deepEqual(findInternalOnlyFieldPaths(publicData),[]);const exported=buildPublicationExportDryRun({contentType:"activity",publicData,mediaManifest:[]});assert.equal(exported.safe,true);}});
test("只依欄位結構阻擋nested internalNotes與canonical直出",()=>{const injected={title:"公開標題",nested:{internalNotes:"SECRET-INTERNAL-PUBLICATION-TEST"}};assert.deepEqual(findInternalOnlyFieldPaths(injected),["$.nested.internalNotes"]);assert.equal(buildPublicationExportDryRun({contentType:"class_result",publicData:injected,mediaManifest:[]}).safe,false);const directCanonical=buildPublicationExportDryRun({contentType:"class_result",publicData:klass(),mediaManifest:[]});assert.equal(directCanonical.safe,false);});
test("合法公開欄位可含SECRET文字，export schema仍無internalNotes",async()=>{const secret="SECRET-INTERNAL-PUBLICATION-TEST";const result=await run({data:{...klass(),publicNotes:secret,internalNotes:secret}});assert.equal(result.valid,true);assert.equal(findInternalOnlyFieldPaths(result.publicData).length,0);assert.equal(buildPublicationExportDryRun({contentType:"class_result",publicData:result.publicData,mediaManifest:result.mediaManifest}).safe,true);});
test("draft狀態、缺圖與新內容缺封面會阻擋",async()=>{const status=await run({draftStatus:"draft"});assert.ok(status.errors.some(x=>x.code==="draft_not_validated"));const missing=await run({media:[]});assert.ok(missing.errors.some(x=>x.code==="media_missing"));const data={...klass(),coverAssetId:null};const cover=await run({data,legacy:false,media:[]});assert.ok(cover.errors.some(x=>x.code==="cover_required"));});
test("cms_draft逐項驗證Storage checksum、alt、rights與portrait",async()=>{const data={...klass(),galleryAssetIds:[]};const asset=media({legacyAssetKey:null,source:"cms_draft",bucket:"cms-drafts",objectPath:"safe/file.jpg",altText:"",rightsStatus:"unknown",containsPortrait:"unknown"});data.coverAssetId=asset.id;const result=await run({data,legacy:false,media:[asset],verifyStorage:async()=>({exists:true,sha256:"b".repeat(64)})});for(const code of ["media_alt_required","media_rights_unknown","media_portrait_unknown","storage_checksum_mismatch"])assert.ok(result.errors.some(x=>x.code===code));});
test("cms_draft拒絕其他content、draft或owner的media",async()=>{const data={...klass(),galleryAssetIds:[]};const asset=media({legacyAssetKey:null,source:"cms_draft",contentId:"wrong",draftId:"wrong",createdBy:"wrong",bucket:"cms-drafts",objectPath:"safe/file.jpg",altText:"替代文字",rightsStatus:"owned",containsPortrait:false});data.coverAssetId=asset.id;const result=await run({data,legacy:false,media:[asset],contentId:"content",draftId:"draft",userId:"user"});assert.ok(result.errors.some(x=>x.code==="media_unauthorized"));});
test("checksum涵蓋revision、公開資料、cover與gallery順序",async()=>{const base={publicData:{id:"x",coverAssetId:"cover"},mediaManifest:[{id:"a"},{id:"b"}],sourceRevision:1};const a=await publicationSnapshotChecksum(base);assert.notEqual(a,await publicationSnapshotChecksum({...base,sourceRevision:2}));assert.notEqual(a,await publicationSnapshotChecksum({...base,publicData:{...base.publicData,id:"y"}}));assert.notEqual(a,await publicationSnapshotChecksum({...base,publicData:{...base.publicData,coverAssetId:"other"}}));assert.notEqual(a,await publicationSnapshotChecksum({...base,mediaManifest:[...base.mediaManifest].reverse()}));});
test("活動公開投影格式化canonical日期且排除internalNotes",async()=>{const data={id:"116-001",year:116,name:"地方文化學習活動",startDate:"2027-08-06",endDate:null,dateLabel:"舊標籤",districts:["朴子市"],venue:"測試場地",projectName:null,activityType:"講座",topic:"地方文化",sdgs:["SDG 4"],summary:"這是一段符合最小長度的活動效益摘要，用來驗證發布前資料。",participants:20,partnerOrganizations:null,leader:null,keywords:[],videoUrl:null,relatedUrl:null,featured:false,internalNotes:"ACTIVITY-SECRET",publicNotes:null,coverAssetId:"cover-key",galleryAssetIds:[]};const result=await run({contentType:"activity",data,legacy:true,media:[media()]});assert.equal(result.valid,true);assert.equal(result.publicData.dateLabel,"8/6");assert.equal(JSON.stringify(result.publicData).includes("ACTIVITY-SECRET"),false);});
test("XSS文字與javascript URL在final validation阻擋",async()=>{const xss=await run({data:{...klass(),description:"這是一段足夠長但包含 <script>alert(1)</script> 的不安全公開內容。"}});assert.ok(xss.errors.some(x=>x.code==="unsafe_public_content"));const activity={id:"116-001",year:116,name:"地方文化學習活動",startDate:"2027-08-06",endDate:null,dateLabel:"8/6",districts:["朴子市"],venue:"測試場地",projectName:null,activityType:"講座",topic:"地方文化",sdgs:["SDG 4"],summary:"這是一段符合最小長度的活動效益摘要，用來驗證發布前資料。",participants:20,partnerOrganizations:null,leader:null,keywords:[],videoUrl:null,relatedUrl:"javascript:alert(1)",featured:false,internalNotes:null,publicNotes:null,coverAssetId:"cover-key",galleryAssetIds:[]};const bad=await run({contentType:"activity",data:activity,legacy:true,media:[media()]});assert.ok(bad.errors.some(x=>x.code==="url.httpsOnly"));});
