import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const sql=await readFile(new URL("../../supabase/migrations/202608280002_publication_snapshot_workflow.sql",import.meta.url),"utf8");
const manifestV2=await readFile(new URL("../../supabase/migrations/202609010001_publication_snapshot_media_manifest_v2.sql",import.meta.url),"utf8");
const edgeIndex=await readFile(new URL("../../supabase/functions/prepare-publication-snapshot/index.ts",import.meta.url),"utf8");
const edgeHandler=await readFile(new URL("../../supabase/functions/prepare-publication-snapshot/handler.ts",import.meta.url),"utf8");
test("migration保留baseline並新增draft publication payload與唯一鍵",()=>{assert.match(sql,/add column public_data jsonb/i);assert.match(sql,/add column publication_validation jsonb/i);assert.match(sql,/where snapshot_source = 'draft'/i);const beforeFunction=sql.slice(0,sql.indexOf("create function public.canonical_jsonb_text"));assert.doesNotMatch(beforeFunction,/(update|delete from|insert into) public\.(content_items|content_drafts|media_assets|publication_snapshots)/i);});
test("RPC限service role、鎖revision並拒絕projection manifest checksum差異",()=>{assert.match(sql,/auth\.role\(\).*service_role/is);assert.match(sql,/for update/i);assert.match(sql,/draft revision changed/i);assert.match(sql,/public projection mismatch/i);assert.match(sql,/media manifest mismatch/i);assert.match(sql,/publication checksum mismatch/i);assert.match(sql,/revoke all on function public\.prepare_publication_snapshot[\s\S]*grant execute[\s\S]*service_role/i);});
test("RPC不切published pointer、不寫Storage GitHub或草稿",()=>{const body=sql.slice(sql.indexOf("create function public.prepare_publication_snapshot"));assert.doesNotMatch(body,/update public\.content_items/i);assert.doesNotMatch(body,/(insert into|update|delete from) public\.(content_drafts|media_assets|github_publications)/i);assert.doesNotMatch(body,/(insert into|update|delete from) storage\.objects/i);});
test("Stage 7A.1 additive RPC凍結完整既有media metadata且不回填baseline",()=>{for(const key of ["mimeType","extension","byteSize","width","height","altText","caption","credit","rightsStatus","containsPortrait","portraitConsent","uploadStatus"])assert.match(manifestV2,new RegExp(`'${key}'`));assert.match(manifestV2,/create or replace function public\.prepare_publication_snapshot/i);assert.doesNotMatch(manifestV2,/(update|delete from|insert into) public\.(content_items|content_drafts|media_assets)/i);assert.doesNotMatch(manifestV2,/(update|delete from) public\.publication_snapshots/i);});
test("Stage 7A.1 authoritative RPC依DB row重建manifest並拒絕browser偽造metadata",()=>{assert.match(manifestV2,/media\.mime_type[\s\S]*media\.byte_size[\s\S]*media\.alt_text[\s\S]*media\.portrait_consent/i);assert.match(manifestV2,/p_media_manifest is distinct from v_expected_manifest/i);assert.match(manifestV2,/media manifest mismatch/i);});
test("Edge只接受snapshot action識別並從server查詢完整media metadata",()=>{for(const column of ["mime_type","extension","byte_size","width","height","alt_text","caption","credit","rights_status","contains_portrait","portrait_consent","upload_status"])assert.match(edgeIndex,new RegExp(column));const input=edgeHandler.slice(edgeHandler.indexOf("type Input"),edgeHandler.indexOf("type Preparation"));assert.doesNotMatch(input,/mediaManifest\??\s*:/);assert.doesNotMatch(input,/altText\??\s*:/);assert.match(edgeIndex,/PUBLICATION_SCHEMA_VERSION/);});
