import test from "node:test";
import assert from "node:assert/strict";
import { createPreparePublicationSnapshotHandler } from "../../supabase/functions/prepare-publication-snapshot/handler.ts";

const origin="https://yimi-story-admin.pages.dev",draftId="11111111-1111-4111-8111-111111111111";
const preparation={valid:true,errors:[],warnings:[],validation:{revision:4},checksum:"a".repeat(64),mediaManifest:[],publicData:{id:"CR-116-001"}};
const request=(body={action:"validate",draftId,expectedRevision:4},requestOrigin=origin)=>new Request("https://example/functions/v1/prepare-publication-snapshot",{method:"POST",headers:{origin:requestOrigin,authorization:"Bearer safe-test","content-type":"application/json"},body:JSON.stringify(body)});
function deps(status="active"){let creates=0;return{state:()=>creates,value:{verify:async()=>({status,userId:"22222222-2222-4222-8222-222222222222"}),prepare:async()=>preparation,create:async()=>{creates++;return{created_at:"2026-08-28T00:00:00Z",source_revision:4,checksum_sha256:preparation.checksum,status:"ready"};}}};}

test("active admin可先validate再create且response只含安全摘要",async()=>{const d=deps();let response=await createPreparePublicationSnapshotHandler(origin,d.value)(request());assert.equal(response.status,200);const checked=await response.json();assert.equal(checked.preparation.valid,true);assert.equal("publicData" in checked.preparation,false);assert.equal("mediaManifest" in checked.preparation,false);response=await createPreparePublicationSnapshotHandler(origin,d.value)(request({action:"create",draftId,expectedRevision:4}));assert.equal(response.status,200);const created=await response.json();assert.equal(created.snapshot.source_revision,4);assert.equal("snapshot_data" in created.snapshot,false);assert.equal(d.state(),1);});
test("invalid request、inactive admin與unknown origin阻擋",async()=>{const active=deps();assert.equal((await createPreparePublicationSnapshotHandler(origin,active.value)(request({action:"create",draftId:"bad",expectedRevision:4}))).status,400);assert.equal((await createPreparePublicationSnapshotHandler(origin,deps("inactive").value)(request())).status,403);assert.equal((await createPreparePublicationSnapshotHandler(origin,active.value)(request(undefined,"https://attacker.example"))).status,403);});
test("validation失敗不建立snapshot且revision race回409",async()=>{const d=deps();d.value.prepare=async()=>({...preparation,valid:false,errors:[{field:"media",code:"missing",message:"missing"}]});const invalid=await createPreparePublicationSnapshotHandler(origin,d.value)(request({action:"create",draftId,expectedRevision:4}));assert.equal(invalid.status,422);assert.equal(d.state(),0);const race=deps();race.value.prepare=async()=>{throw new Error("stale_revision")};assert.equal((await createPreparePublicationSnapshotHandler(origin,race.value)(request())).status,409);});
test("CORS只允許正式admin origin且無wildcard",async()=>{const response=await createPreparePublicationSnapshotHandler(origin,deps().value)(new Request("https://example",{method:"OPTIONS",headers:{origin}}));assert.equal(response.status,204);assert.equal(response.headers.get("access-control-allow-origin"),origin);assert.notEqual(response.headers.get("access-control-allow-origin"),"*");});
